### ISSUE TITLE
Reinstalling App

### ISSUE THREAD

**Issue by Storm562** [itsMeDavidV/Watchla-Support#10]
Hi,
I had to reformat my watch with the last apple update, when I go to the app store to download the app, the link button isn't active,
it just shows "Purchased"
Thanks
Paul

**Comment by itsMeDavidV** [comment]
Hi @Storm562

It's recommend to download Watchla directly from the App Store app right on your Apple Watch. This should trigger a Watchla download almost immediately on your Apple Watch.

Since Watchla is a stand-alone watch app with no iOS companion app, downloading it using the App Store on your phone can be spotty and is not recommended.

A lot of times after users buy Watchla on the App Store on their phone, a “Purchased” indicator label will appear, but there will be no option to download. This is a misstep by Apple. Just open the App Store app on your watch, search for Watchla, and tap the download button.

Let me know if you still have issues going forward,
-David

**Comment by Storm562** [comment]
I used my watch, there's no download option, just a "Buy" option?
It looks like it will charge me again?
Thanks
Paul

**Comment by itsMeDavidV** [comment]
So your paired iOS device says "Purchased", but your Apple Watch says "Buy"? If so, that's definitely unusual. I would make sure that your Apple Watch is using the same Apple account as the paired iOS device that you used to buy Watchla. You could have been signed out when reformatting your Apple Watch. If they are indeed running the same account and this problem persists, then I would definitely recommend that you contact Apple Support as you shouldn't have to pay twice and they would most likely be able to rectify this issue for you. Unfortunately, Watchla has no control over downloading or buying the app, Apple does. Please do let me know the outcome of this and sorry to hear that you're facing this issue.

**Comment by Storm562** [comment]
I just wanted to see what happened if I said purchase, it acknowledged that I already purchased it, so we’re all good
Thank you
Paul

**Comment by itsMeDavidV** [comment]
@Storm562 That's good to hear! Sounds like just a discrepancy between iOS & WatchOS App Store. Thanks for letting me know.
