### ISSUE TITLE
Battery state on Apple Watch

### ISSUE THREAD

**Issue by atursch** [itsMeDavidV/Watchla-Support#101]
The battery state always shows 0% at the Apple Watch face.

**Comment by itsMeDavidV** [comment]
Hi @atursch this is due to an issue with back up vehicle data implementation that affects some Watchla users who's vehicles have less that ideal internet connections or are prone to fall into deep sleep and can't be woken quickly. This is being a worked on (a top priority) and a fix is coming soon.

Sorry for the inconvenience this causes.

As a work around for the time being it might be productive to esquire both your Apple Watch and Tesla have good connections to the internet and that you keep Sentry Mode on so that your vehicle doesn't fall into deep sleep.

**Comment by wandellms** [comment]
This is happening to me, my compilation will show 0% unless I open the app and then it refreshes. I have great internet at my location

**Comment by itsMeDavidV** [comment]
Hi @wandellms a solution is being tested in beta with good results. It will be included in the next update.

**Comment by itsMeDavidV** [comment]
Hi @atursch & @wandellms I just wanted to let you know that a new update (v3.02) that addresses this issue has been released earlier today.

You can update here: https://apps.apple.com/us/app/watchla/id1546599747

**Comment by atursch** [comment]
Hi. Just installed the update and the issue still exists. Pls check again. Thanks

**Comment by itsMeDavidV** [comment]
Hi @atursch can you send over your Watchla support code so I can investigate, thanks!

**Comment by doose7** [comment]
This is also still happening to me in the latest version. 

Support code vvdHHksmLU

**Comment by itsMeDavidV** [comment]
@doose7 sorry to hear that, will investigate

**Comment by wandellms** [comment]
It is better, but it still happens after a period of timeOn Feb 17, 2023, at 12:49, David Villegas ***@***.***> wrote:﻿
@doose7 sorry to hear that, will investigate

**Comment by itsMeDavidV** [comment]
@wandellms nice good to hear that it's improved at least. Watchla is currently in the process of changing how it backs up vehicle data as well as adding support for backing up multiple vehicles.

Granted this should help immediately, however you will notice much more significant results when Watchla switches to Apple's new preferred framework for Watch Face complications--this will be happening after the next couple of Bluetooth updates.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
