### ISSUE TITLE
Set Default Vehicle 

### ISSUE THREAD

**Issue by SarcasticAY** [itsMeDavidV/Watchla-Support#107]
How do you set a default vehicle on the app and watch when you have more than 1 vehicle associated with your account.  The app currently defaults to the first listed vehicle each time I open or minimize the app on the phone or the watch 
Thanks,

**Comment by itsMeDavidV** [comment]
Hi @SarcasticAY to select another vehicle, goto Preferences and tap the vehicle cell on on the top of the screen. This will give you a list of other vehicles to designate as your Selected Vehicle!

This can be done both on the iOS and watch app and a change to one will reflect on both.

**Comment by SarcasticAY** [comment]
Hi David,

I’ve done as you instructed but when I close out of the app, it defaults
back to the fist listed vehicle.

Thanks,

**Comment by itsMeDavidV** [comment]
@SarcasticAY hmm sorry to hear that. If possible, can you upload a video of this happening so that I can ID any cues that might point to an issue?

Also can you send over your Support Code to https://watchla.app/contact so that I can check any relevant error logs that might point to why this occurring. Thanks!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
