### ISSUE TITLE
Bluetooth working intermediate? 

### ISSUE THREAD

**Issue by SYCC148** [itsMeDavidV/Watchla-Support#110]
Why the Watchla app on my watch needs reload /refresh to get my Tesla to unlock? Is it normal? Your latest Watchla version which supports Bluetooth as key doesn’t seem like it’s working like a phone that works most of time when a phone near the door. What am I missing?

**Comment by itsMeDavidV** [comment]
@SYCC148 Sorry I have trouble understanding your question. Are you saying you need to wait for Watchla to load vehicle data before Bluetooth connects for you (which that shouldn't be the case)? Or are you referring to the need for the Watchla watch app to sometimes be opened in order to connect to your vehicle? 

If you are referring to the latter, here is a helpful tweet on this topic: https://twitter.com/WatchlaApp/status/1616538888805445633?s=20&t=a_tuy-U6CmPYkrvPBL4-HQ

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
