### ISSUE TITLE
App must be brought up on watch for the door to open.  Is this normal or a setting issue?

### ISSUE THREAD

**Issue by cso253** [itsMeDavidV/Watchla-Support#116]

**Comment by itsMeDavidV** [comment]
Hi @cso253 Sometimes you may need to open the app for Watchla to connect to your vehicle over Bluetooth and unlock.

This is because, due to Apple Watch limitations, Watchla cannot guarantee that it will always be able to connect to your vehicle via Bluetooth while the app is in the background. I hope that Apple will become more lenient with this in watchOS 10, but for now Watchla is being optimized to best deal with this limitation. 

You can read more about this here: https://twitter.com/WatchlaApp/status/1616538888805445633
