### ISSUE TITLE
Bluetooth not even getting past “connecting”

### ISSUE THREAD

**Issue by AaronJenTes** [itsMeDavidV/Watchla-Support#121]
Hi. Firstly it’s fantastic app, works well. I’m have a series 1 Apple Watch so my os6.3 is too low to have shortcuts which is a massive loss on the Siri commands but cei la vie. My main issues is the Bluetooth connection. I have my 2022 model 3 already allowing mobile access. My iPhone key is working. My Apple Watch Bluetooth is turns on and is picking up other Bluetooth devices. I followed the instructions to be in the car and wait for the key card prompt but the Bluetooth set up is stuck on “connecting” any help would be very much appreciated. If you have a solution for the shortcuts for series 1 running OS6.3 then great also. Cheers

**Comment by itsMeDavidV** [comment]
Hi @AaronJenTes sorry about shortcuts, that is a real shame that wOS6.3 doesn't support :/

About your issue: You are most likely experiencing a very rare issue [mentioned here](https://github.com/itsMeDavidV/Watchla-Support/issues/120) and I'm very happy to let you know that this was _Just_ fixed! 

Would you like me to send you over a beta invite so that you can test this fix? If so, send me an email here: david@watchla.app and I'd be happy to send you an invite! 

Additionally after some further beta testing we will begin to roll this out to the App Store in update v3.4.2 in a week or so.

**Comment by AaronJenTes** [comment]
Hi David, that is fantastic news. Many thanks for such a prompt reply and great support. I will email you now to sign up to the beta. PS very happy with the app so great work 👍

**Comment by itsMeDavidV** [comment]
You're very welcome!
