### ISSUE TITLE
App version 3.4.2 not connecting to Bluetooth

### ISSUE THREAD

**Issue by skim852** [itsMeDavidV/Watchla-Support#122]
I installed the new app version 3.4.2 and bluetooth successfully connected at first. The phone no longer connects to Tesla anymore. It displays not connected when I’m in the car.

**Comment by itsMeDavidV** [comment]
Hi @skim852 thanks for reporting, I'll investigate and get back to you. Can send over your new support code? Your previous one has changed since downloading the beta app. Thanks!

**Comment by skim852** [comment]
1fPEOdDDq3


On Mar 16, 2023, at 11:29 AM, David Villegas ***@***.***> wrote:

﻿

Hi @skim852<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskim852&data=05%7C01%7C%7C1b6f85c17a984b37bde008db264c66f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638145881808884120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D5IyELPcB4iLXICnnxa542NMLMsrXyjOMJSVcOhEGWg%3D&reserved=0> thanks for reporting, I'll investigate and get back to you. Can send over your new support code? Your previous one has changed since downloading the beta app. Thanks!

**Comment by itsMeDavidV** [comment]
Hi @skim852 so after checking there are no reported Bluetooth errors associated with your support code. When you say "the phone no longer connects" are you referring to the Watchla iOS app, the Tesla app, your phone in general or were you referring to the Watchla watch app?

I did see that on the watch app, your watch did not connect to your Tesla. When this happened, approximately how far were you from your vehicle? Would you say you were within 10 meters or less from the vehicle?

**Comment by skim852** [comment]
The Watchla watch app no longer connects to my Tesla via Bluetooth.

On Mar 16, 2023, at 2:07 PM, David Villegas ***@***.***> wrote:

﻿

Hi @skim852<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskim852&data=05%7C01%7C%7Cb48711eb368c48ae038f08db26626970%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638145976332432103%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vmlRcKTh0luj5T9EIO88fEpRRYFjwUfV8guHo82Cs3Q%3D&reserved=0> so after checking there are no reported Bluetooth errors associated with the support code. When you say "the phone no longer connects" are you referring to the Watchla iOS app, the Tesla app, your phone in general or were you referring to the Watchla watch app?

**Comment by skim852** [comment]
Update: It takes several mins for the Watch to connects to Tesla

**Comment by itsMeDavidV** [comment]
Hi @skim852 after reviewing logs associated with your new support code, I can confirm that Watchla has corrected itself and you are now able to connect to your vehicle over Bluetooth via Watchla :)

> Update: It takes several mins for the Watch to connects to Tesla

Additionally, as for connecting to your Tesla over the internet: Watchla relies on Tesla Servers to connect to your vehicle. I would recommend ensuring that both your vehicle and devices have ideal connections to the internet. Sometimes parking in a garage or parking garage or connecting to home WiFi from a long distance can hinder the vehicle's ability to connect to the internet at ideal speeds. Additionally if you actively keep Sentry Mode off, this can also be a contributor as your vehicle will be more prone to falling into deep sleep, which in turn causes your vehicle to take longer to wake and connect to Tesla Servers when prompted to do so.

Also since you're now connected over Bluetooth, Watchla can wake your vehicle over Bluetooth (when nearby) making overall connection times much faster.

**Comment by skim852** [comment]
Thanks for the support and additional info.
