### ISSUE TITLE
"Do not wake" behavior

### ISSUE THREAD

**Issue by Steffi3rd** [itsMeDavidV/Watchla-Support#127]
Hi ! 

With my bro we've seen that **data is not sync in realtime** contrary to Tesla app

We've tried two scenarios and don't understand results : 

1 / Do not wake ON + Do not wake in background ON _(time : 12h50)_
- When we opened Tesla app, it displays 19% battery. ✅ 
- On Apple Watch homescreen, Watchla complications displays : 16% ❌ (not updated why?)
- When open Watchla app on Apple Watch : it displays 11% ❌ (not updated why?)

![Capture d’écran   2023-03-30 à 12 49 43](https://user-images.githubusercontent.com/814410/228843966-879cb4ce-601b-4726-8da6-5ec28d9f8ee4.jpeg)
![ss](https://user-images.githubusercontent.com/814410/228844128-7bb5c5b1-3b37-4750-af6a-2456bec7402c.jpg)

2 / Do not wake OFF + Do not wake in background OFF _(time : 14h46)_
- When we opened Tesla app, it displays 60% battery ✅ 
- On Apple Watch homescreen, Watchla complications displays : 57% ❌ (not updated why? Do not wake in the background is not enabled, **we expect that when we raise our wrist, it's automatically updated to 60%,** right ?)
- When open Watchla app on Apple Watch : it displays 57% then after 4 seconds 60% ⚠️ (why do we have to open the app to see updated values? It doesn't make sense if we have to it manually 🤔)

![incoming-D0977A06-800C-4281-924F-0CA791FFBD91](https://user-images.githubusercontent.com/814410/228844774-212d75b3-42ab-4bb6-8c86-69d6430aa463.jpeg)
![incoming-483FF3BF-61EB-4B4F-AA62-DBBDB8DD7076](https://user-images.githubusercontent.com/814410/228844782-5123f742-ab5d-4f6e-abac-6a882b24350f.jpeg)
![incoming-BA55764D-940F-4E70-954D-5035E6D51E3D](https://user-images.githubusercontent.com/814410/228844779-c54d6b47-b36a-494d-8a62-7d08b7d3cc11.jpeg)
![incoming-CB6B306D-A38F-44DB-855A-7475B3297DC1](https://user-images.githubusercontent.com/814410/228844776-11c9d551-80b0-461f-b096-96f6003924ae.jpeg)

We think we are biased by the value displayed on Apple Watch homescreen because it may be missing the crucial information (like on the Tesla App Widget) **"updated XX hours and YY seconds ago"**

Or else we have it all wrong, so we need more explainations about Do not wake. 

Additionnal questions :  What is the purpose of the feature : "Do not wake in background: ON"? 
If enabled what we can/cannot do? 

Thank you!

**Comment by itsMeDavidV** [comment]
Hi @Steffi3rd first off, this is an awesome write-up, thank you for putting quality time and effort into these 2 questions 😊

1: Do Not Wake stops Watchla from waking your vehicle completely, even while the app is in the foreground. If you have Do Not Wake on you can still opt to manually wake. Do Not Wake in Background, stops Watchla from waking your vehicle while the Watchla app is in the background (eg: for things like complication updates and critical vehicle alerts). 

Do Not Wake is meant only for those who are extremely conscious of their vehicle's charge state. Eg: they don't have reliable access to charging or home charging and need to preserve every % point possible for their day-to-day driving.  

Since your vehicle needs to be awake to retrieve vehicle data like charge, climate and vehicle states, **Watchla doesn't recommend Do Not Wake or Do Not Wake in Background**, except for the extreme and rare condition outlined above, because in 2023 there is exponentially more chargers than when Watchla was originally developed and therefor access to charging and vehicle battery management efficiency has increased dramatically reducing the need for Do Not Wake.

So to answer your first question, this is the reason your complications did not update charge state data when you had Do Not Wake on: 

> your vehicle needs to be awake to retrieve vehicle data like charge, climate and vehicle states

2: Complication updates while in background are regulated and limited by watchOS to preserve your Apple Watch's battery life. Therefor Watchla is not at liberty to be able to update complications in an unlimited frequency capacity, in fact given these limitations, Watchla--at its fastest--is only allowed to update complications while in background around every 15 minutes and even this can be throttled by your Apple Watch's battery management software.

So given these limitations by the Apple Watch, unfortunately this:

> we expect that when we raise our wrist, it's automatically updated to 60%, right ?

is not possible in Apple Watch apps. There are _some (very few)_ Apple Watch apps that can do this and they are either System Apple Watch apps (owned by Apple) or they are time-sensitive health related apps given special permission by Apple to bypass battery management limits (eg: a heart rate app)

There are still work-arounds to this limit that can slightly increase the frequency of updates to complications that will be adopted when Watchla migrates to its new complication stack (this is on the docket and will happen soon), however until Apple makes changes to watchOS we will always have these limits and this:

> we expect that when we raise our wrist, it's automatically updated to 60%, right ?

won't be guaranteed for apps like Watchla :(

**Comment by Steffi3rd** [comment]
Thank you for your answer, very clear

Do you is it possible to add **"updated XX hours and YY seconds ago".** ?
We think it's pretty important to know what are the statut but also to know the last time this status was updated

**Comment by itsMeDavidV** [comment]
Yes, I'll definitely look into adding that!
