### ISSUE TITLE
Vehicle data error

### ISSUE THREAD

**Issue by AlainBijl** [itsMeDavidV/Watchla-Support#134]
Hi,

The (Watch)app works perfectly, but the widgets always gives Vehicle data error. 

BR,
Alain
![IMG_7157](https://github.com/itsMeDavidV/Watchla-Support/assets/16701690/273d034e-da1e-40c8-a4fe-1e71fab1571f)
![IMG_7158](https://github.com/itsMeDavidV/Watchla-Support/assets/16701690/cf0a0474-f791-4222-9d97-41410af0ed1f)

**Comment by itsMeDavidV** [comment]
Hi @AlainBijl sorry to hear that, can you please submit over your Watchla support code here: https://watchla.app/support so that this issue can be investigated?

**Comment by AlainBijl** [comment]
Done!

**Comment by itsMeDavidV** [comment]
Hi @AlainBijl sorry for the wait, Watchla gets a lot of messages these days. 

After reviewing, it seems as though your iOS device is blocked from your Do Not Wake settings. In order for your vehicle to send relevant, real time data (like charge state stats) it needs to be awake. However because of your Do Not Wake configuration, Watchla has been blocked from waking your vehicle so that it can retrieve this data from your vehicle.

In order to ensure that this specific widget works properly, you will probably have to leave Do Not Wake off. 

Since Tesla's battery management and efficiency is getting better, we really only recommend turning on Do Not Wake in extreme circumstances where charging is not easily accessible. 

Hope this helps! Please feel free to shoot any questions my way if you have them.

-David
