### ISSUE TITLE
Car will not start using Apple Watch application watchla

### ISSUE THREAD

**Issue by Jbmsocal** [itsMeDavidV/Watchla-Support#14]
Error message - cannot start car remotely — all other functionality seems to work except SIRI COMMANDS - not sure why

**Comment by itsMeDavidV** [comment]
Hi Sorry to hear remote start is not working for you. Can you please email me your support code so that I can directly identify what is causing remote start to not work for you? From there I will be in a better position to offer a solution.

My email is david@villegasventures.co

**To find your support code:**
From the Watchla main screen, goto "Preferences" -> "support/feedback" -> "Support code"

As for Siri, I want to preface what I'm about to say below with the fact that Watchla will be acquiring Siri Shortcut capability very soon (a big upgrade) and will be dumping the old Siri framework that it currently utilizes so the below info won't apply for much longer.

**To enable Siri for Watchla:**
Goto the Settings app on your Apple Watch -> scroll down & select "Siri", scroll down & select "Use with Siri", and then turn on "Watchla".

If the above doesn't fix your Watchla-related issues with Siri, please let me know by replying to this thread.

Hope this bit of info helps!
-David

**Comment by Jbmsocal** [comment]
Hi David the support code is WAJ41F7WOH
________________________________

**Comment by Jbmsocal** [comment]
Hi David I was able to resolve the Siri issue by following your instructions I’ll await your response to find out why the start car command doesn’t work

Thanks in advance
Jeff
________________________________

**Comment by Jbmsocal** [comment]
Hi David I have attached a screenshot of the message on getting on my Apple Watch I’ve seen many other users are having the same issue I’ll double check the password and everything is correct. [Image.jpeg]
________________________________

**Comment by itsMeDavidV** [comment]
@Jbmsocal Hi Jeff, sorry for the delay. I wasn't able to see your screenshot, it seems Github is being a bit wonky. 

However after looking at your error logs via your support code and also investigating further, there does seem to be an app-wide bug related to remote start.

I have no way of confirming, but you most-likely did nothing wrong and entered your password correctly, the fault is with Watchla.

I have gone ahead and fixed this issue and the fix should be included in an App Store update of Watchla, most likely this weekend or early next week.

Thanks again for reporting this!
-David

PS: I'll close this issue when the new update is available on the App Store.

**Comment by itsMeDavidV** [comment]
Happy to report that a fix for this is now live in version 1.92!

**Comment by Jbmsocal** [comment]
Thanks David - How do I update this version?   Since you don't have the
"Watchla" app on my iphone - I'm unfamiliar with updating a "watch only
app" ...

thanks in advance,
Jeff

**Comment by itsMeDavidV** [comment]
@Jbmsocal hi Jeff, to update Watchla just navigate to the App Store app on your Apple Watch itself, search for Watchla and tap update. 

Let me know how Remote Start works for you in the new version!

-David

**Comment by itsMeDavidV** [comment]
Just a quick update on remote start: An additional bug that might cause failure was identified and fixed in the newly updated version of Watchla, version 1.93, which was just now released on the App Store. To ensure remote start works properly, I recommend updating to 1.93!
