### ISSUE TITLE
Stuck connecting Bluetooth on v2023.26.7

### ISSUE THREAD

**Issue by csmckinlay** [itsMeDavidV/Watchla-Support#145]
I connected my watch this morning when running 2023.26.1. Then realized I was logged into the wrong account. But before I switched accounts my vehicle updated to 2023.26.7.  
now I cannot get the watch to connect Bluetooth.  Stuck on Initializing or Connecting. 
I’ve deleted all the keys and all the Bluetooth devices, uninstalled watchla from my phone and my watch twice. Nothing has fixed this. Thanks for the help.

**Comment by itsMeDavidV** [comment]
Hi @csmckinlay can you please send over your Watchla support code via https://watchla.app/support so this can be investigated? Thanks!

**Comment by csmckinlay** [comment]
Sent via Contact

**Comment by mikeljungbergtvedt** [comment]
I have the same issue. I am on 2023.26.6 and cannot connect with Watchla APP. The car is configured correctly and identifies lots of other bluetooth devices, but not my Apple Watch. The APP is installed and my car is selected and displayed on the watch.

**Comment by JalinEnterprisesLLC** [comment]
I have the same issue of no Bluetooth digital key connection after installing tesla version 2023.26.7

**Comment by itsMeDavidV** [comment]
Hi all, thank you so much for reporting this. A little update:

It looks like Tesla has changed some things. After some investigation Watchla was able to track down those changes that broke Bluetooth for 2023.26 versions and is now in the process of adapting/updating. 

An App Store update will be out in the coming days, hopefully by Thursday or Friday (PST)

Thanks again for your patience and time taken to report this.

**Comment by itsMeDavidV** [comment]
Hi everyone just a quick update, there is a beta update that has been released to address this issue. If you are facing this issue and would like access, please reach out via https://watchla.app/contact

With the following:

- A reference to this issue
- Your Watchla support code (found in Support/Feedback screen)

**Comment by JalinEnterprisesLLC** [comment]
Sorry but no change with latest 3.4.6 update support code :
WyTDSY3D4o

**Comment by itsMeDavidV** [comment]
Alright everyone, so while there is an update out, we have determined that it doesn't fully fix everything..

Tesla has made a change in 2023.26.7 that right now only affects some vehicles--at random. Most people are able to connect fine, some people are not able to connect at all. 

We have pinpointed what was not clear before and are adapting.

There will be a beta out today with further changes and fixes. If you have not yet requested beta and want to do so, please reach out via https://watchla.app/contact with the following:

- your Watchla support code
- a link to this issue or mention of it for reference

Thank you everyone for your patience as this is resolved.

**Comment by itsMeDavidV** [comment]
The complete fix is out in beta. If you would like to test, the build is v3.4.7 (297)

Otherwise, the App Store update should be out hopefully this weekend or by Monday.

If you requested beta, check your Watchla iOS app for updates about getting into beta.

**Comment by JalinEnterprisesLLC** [comment]
Hi David -
unfortunately the latest Beta 3.4.7 still does not work on my Model 3 (2018) with he 2023.26.7.  My Support code is: HCGLRtgfMZ.

IF it helps you at all I also had the Watch for Tesla app (I don’t think that code is publicly availabe) that because they had a lot of connection and walk away issues, I moved to Watchla and it has worked great since I first uploaded it until this latest issue.  I reloaded the Watch for Tesla  app and they were experiencing the same or related issue. They just updated there beta 10 1.3.9 to 1.3.10 and that appeared to fix their app, but again that app has never worked reliably with the walk away feature and your’s has so I really want to help any way I can to assist you in getting this fixed.

Thanks for all your good work,
Chris Mathewson

**Comment by itsMeDavidV** [comment]
Unfortunately there still seems to be a small amount of people who still face this issue. Watchla will be releasing v3.4.8 which has prioritized a different way of identifying a Tesla via Bluetooth. This is a very new way for the 3rd party community (as in this was discovered literally today and has not been documented yet) so there will be some validation needed. 

Apple is currently reviewing v3.4.8 beta, however since it is Saturday night in California right now, this process might be delayed.

If you would like to help validate v3.4.8 beta and have not requested beta, please do so.

**Comment by csmckinlay** [comment]
Ok understood. I am signed up for the beta program. Will I automatically get 3.4.8?


Sent from Yahoo Mail for iPhone


On Saturday, August 12, 2023, 7:05 PM, David Villegas ***@***.***> wrote:




Unfortunately there still seems to be a small amount of people who still face this issue. Watchla will be releasing v3.4.8 which has prioritized a different way of identifying a Tesla via Bluetooth. This is a very new way for the 3rd party community (as in this was discovered literally today and has not been documented yet) so there will be some validation needed.

Apple is currently reviewing v3.4.8 beta, however since it is Saturday night in California right now, this process might be delayed.

If you would like to help validate v3.4.8 beta and have not requested beta, please do so.

**Comment by itsMeDavidV** [comment]
Hi everyone, the v3.4.8 update is now available on the [App Store](https://apps.apple.com/us/app/watchla-for-tesla/id1546599747) and it should fix this issue for you.

Before testing please ensure that your *watch* app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.

Thank you again for your patience.

-David

**Comment by csmckinlay** [comment]
Confirmed Bluetooth is now working v3.4.8 with 2023.26.7.

**Comment by JalinEnterprisesLLC** [comment]
Also confirmed that v3.4.8 appears to work with 2023.26.7.    It didn’t come in as a beta but as a normal release.  Nice work Thanks!

**Comment by JalinEnterprisesLLC** [comment]
Also confirmed that v3.4.8 appears to work with 2023.26.7. It didn’t come in as a beta but as a normal release. Nice work Thanks!On Aug 13, 2023, at 5:47 PM, David Villegas ***@***.***> wrote:﻿
Hi everyone, the v3.4.8 update is now available on the App Store and it should fix this issue for you.
Before testing please ensure that your watch app is up to date. You can check which version the watch app is running by going to Preferences in the Watch app and scrolling all the way down.
Thank you again for your patience.
-David
