### ISSUE TITLE
Support Metric System as well

### ISSUE THREAD

**Issue by lamba92** [itsMeDavidV/Watchla-Support#147]
Outside the US very few uses Fahrenheit or miles. Please support the Metric System as well

**Comment by itsMeDavidV** [comment]
Hi @lamba92 Watchla uses your vehicle's GUI settings to determine what unit of measurement to show. So for example, if your Tesla is set to read distance in Kilometers then Watchla will show distance in Kilometers for that particular vehicle.

If you are seeing behavior that doesn't align with this, it could be bug or it could be due to Watchla not being able to retrieve your vehicle's GUI settings.

If you think this might be a bug can you describe where this issue occurs for you and how frequently it occurs?

Thanks!

**Comment by lamba92** [comment]
Ah I see. I was mislead by widget's complications previews that were not using the IS. Indeed after loading they use the IS, sorry for the false alarm

**Comment by itsMeDavidV** [comment]
All good!
