### ISSUE TITLE
Bluetooth connection spottiness and delays

### ISSUE THREAD

**Issue by yoshiat** [itsMeDavidV/Watchla-Support#157]
Since the update in June/July, the bluetooth connection became very spotty that:
1. The watch seems to take a lot longer to establish bluetooth connection with the vehicle.
2. Even after getting in the vehicle, it occasionally loses connection that the vehicle warns that it's driving w/o a key.

Overall it seems to me that Watchla is sleeping in the background and then loses bluetooth connection depending on situation.

This doesn't happen with the Tesla phone app and one thing I'm noticing is that Tesla app doesn't seem to entirely rely on Bluetooth connection. It seems to remember the location of the vehicle, and the Tesla app checks the status of bluetooth if the location of the vehicle and the phone are close enough.

I don't know if Watchla uses the location information but I feel that's a creative approach to preserve energy and only aggressively try establishing bluetooth connection when the phone/watch is close enough with the vehicle.

**Comment by itsMeDavidV** [comment]
Hi @yoshiat thanks for posting this, will investigate. Also, have you seen [this thread](https://twitter.com/WatchlaApp/status/1638373233115398145)?

**Comment by yoshiat** [comment]
Thanks, I wasn't aware of that thread but it was totally conceivable that the Watch OS may be restricting Bluetooth to preserver battery consumption. If Watchla can nail the balance between preserving battery consumption (both on the watch and the vehicle), responsiveness and reliability, that'll be amazing. I only use Watchla as my car key so that I can leave my phone in the vehicle sometimes :)

**Comment by yoshiat** [comment]
@itsMeDavidV I think the Bluetooth issue that I’m experiencing is related to the state management of the app. I regularly restart the app on the watch and basically that restores Bluetooth connections pretty reliably. Any chance you could initialize the connection state once in a while when the app comes to foreground?

**Comment by itsMeDavidV** [comment]
Hi @yoshiat so that is exactly what Watchla does. Upon the app starting and/or entering foreground it automatically scans for your selected Tesla (or restores its BLE connection with your selected Tesla if it was previously connected). 

Sometimes unfortunately there can be other factors at play that affect BLE connection speed and consistency, like watchOS battery management and changing Bluetooth states in your Tesla. Additionally, Teslas now require an additional step in that it's essential to analyze and confirm a Tesla's Bluetooth Advertisement data whereas before in previous vehicle software versions a Bluetooth name was all that was needed in order to identify and verify the correct Tesla to connect to.

Of course it is possible there are ways in Watchla can improve its Bluetooth handling and that will definitely be addressed in [Watchla's rewrite that is happening now :)](https://x.com/WatchlaApp/status/1711926100736315744)

**Comment by yoshiat** [comment]
Thanks and sorry for my slow response! Yes, I feel the Bluetooth connection is a lot faster and reliable after the massive update. Currently I’m facing the “freeze” issue that others are reporting but I have a sense the Bluetooth connection itself has become much better.

I’ll close this bug once I fully test and validate in the subsequent releases.

**Comment by yoshiat** [comment]
Closing this bug as Bluetooth connectivity greatly improved with the rewrite in 3.5.4 and 3.5.5.
