### ISSUE TITLE
Can’t sign in to watchala 

### ISSUE THREAD

**Issue by troysr** [itsMeDavidV/Watchla-Support#158]
Can’t sign in

**Comment by simjul** [comment]
Getting the same with error that not autorized to sign in

**Comment by itsMeDavidV** [comment]
Hi @troysr & @simjul can you send over your Watchla support codes via https://watchla.app/contact so that this can be investigated? 

Additionally, you can always sign in to Watchla using a Tesla token. 

If you are not familiar with generating a token yourself, you can always generate one using a Tesla token manager.

Here are some Tesla token generator apps that I recommend: 
- [Authla](https://apps.apple.com/us/app/authla/id1546597644) (sister app to Watchla)
- [Auth app for Tesla](https://apps.apple.com/us/app/auth-app-for-tesla/id1552058613)

**Comment by troysr** [comment]
Issue fixed itself I’m all signed in

**Comment by itsMeDavidV** [comment]
@troysr I'm glad to hear that!
