### ISSUE TITLE
Open/Close/Unlock chargers port not unlocking when plugged in

### ISSUE THREAD

**Issue by currawong** [itsMeDavidV/Watchla-Support#165]
This command tries to Open the charge port door when it is already open, plugged in and charging. I am trying to unlock the charge port to remove the plug while car is still charging. The Tesla App shows an Unlock Charge Port button which works.

Watchla tries to Open the already open charge port. ie it issues an Open command.

**Comment by itsMeDavidV** [comment]
Hi @currawong in the Tesla API the open charge port command *is* the unlock charge port command. In both instances (whether unlocking or just opening) the charge port latch is disengaged. There is no stand-alone endpoint in the API for unlocking the charge port bc it's not necessary. When a vehicle is charging however, it's necessary to first stop charging then trigger the open charge port command. This is automatically done both in the Watchla and Tesla apps when you tap the unlock charge port button. 

Issues with this can happen when there is poor connection to the internet for either the vehicle or the device that the app is on, since the app needs to know that you are charging in the first place  in order to stop charging before unlocking and also because the stop charging command can only be sent via a network request (internet connection) while open charge port can be sent via either a network request or Bluetooth. 

Hope this info helps clear up any confusion!

**Comment by itsMeDavidV** [comment]
I also want to add that in cases of slow or less than ideal internet connection, the complication for this might not have enough time to detect whether a vehicle is charging or not when triggering.

Something we'll definitely look into optimizing during [Watchla's rewrite](https://x.com/WatchlaApp/status/1711926100736315744?s=20)

**Comment by currawong** [comment]
There is definitely no internet connection in this situation. It is in an underground carpark with no mobile access. However, what made me raise it as an issue was that the Tesla App knows that the car is charging and displays the unlock button even with no network coverage. I am happy to take screenshots and/or logs next time I try this.

**Comment by itsMeDavidV** [comment]
@currawong interesting, when you tap unlock charge port on the Tesla app with no internet connection does it stop charging before unlocking?

There could be the possibility that a new Protobuf version allows for the transfer of charge state info over Bluetooth, however to my knowledge currently the Tesla 3rd party community is not yet privy to a new version that allows for that.

**Comment by currawong** [comment]
@itsMeDavidV I believe it stops the charge and unlocks but I will test again next week when I visit this parking garage.

**Comment by currawong** [comment]
I did another test this morning. Not the same scenario but it help with understanding what is going on. I went for a bike ride and turned off my mobile. When I got back to the car I launched Watchla on my watch and then opened a door (confirming the car unlocks with just the watch). I then selected open/unlock/close charge port. It opened correctly as expected. However, it also then detected that the port was open and I was able to hit the button again and Watchla issued the correct Close command. 

The difference in this scenario is that the car has internet access via builtin 4G. But this doesn't change the fact that Watchla correctly Closed the charge door without any internet access itself (mobile was switched off)
