### ISSUE TITLE
Siri works for a day then stops working 

### ISSUE THREAD

**Issue by andykab** [itsMeDavidV/Watchla-Support#168]
When I reset my watch Siri command from my Apple 9 watch “open the trunk” seems to work for the day but stops working again the following day. It always returns the message “ You'll need to download an app for your car, or add a car key to the Wallet app.”

**Comment by itsMeDavidV** [comment]
Hi @andykab the errored response Siri gave you indicates that it did not recognize the phrase you gave it. Due to Siri's limitations, you must use the exact Voice Phrase that you designated your Shortcut to have. So for example if your Shortcut's Voice Phrase is "Lock my Tesla", you must tell Siri "Lock my Tesla". Any deviation from that phrase (eg: "Lock my car") will not be picked up by Siri. 

You can edit your Watchla Siri Shortcuts' Voice Phrases either in the Shortcuts app or in the Watchla iOS app by going to Preferences -> Siri Shortcuts -> and tapping on the Shortcut you want to edit.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
