### ISSUE TITLE
Bluetooth neither remote controls want to work 

### ISSUE THREAD

**Issue by aurelien-ideal** [itsMeDavidV/Watchla-Support#180]
Hello there!
I’ve just installed your app which looks amazing…But :
- I’ve the famous 403 error, I understand it’s links with the new Tesla api, so I wait 
- But I’ve also the issue with Bluetooth, impossible to pair my car (m3 2019), see attachment 

Here my support code : BzpSPIPmDE

thanks !🙏 

![IMG_1323](https://github.com/itsMeDavidV/Watchla-Support/assets/5859063/5c279480-f02b-4536-8afa-e0b6e6f23963)

**Comment by itsMeDavidV** [comment]
Hi @aurelien-ideal a Bluetooth change in Tesla vehicle software created this issue. We've since addressed and fixed it in a beta app update that will be out on the App Store soon. This beta app update also fixes the api issue. You're very welcome to test the beta app update if you'd like so that you can begin using Watchla normally. We've sent you an in-app invite that can be found in the Watchla iOS app, if this interests you!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
