### ISSUE TITLE
Could not confirm sign in

### ISSUE THREAD

**Issue by Paddysh** [itsMeDavidV/Watchla-Support#22]
I had to reset my Apple Watch and installed watchla again on the watch.
When I now run Authla and choose „sign in to Watchla“, I get the above mentioned error message. I already deleted Authla on the iPhone and signed in with my Tesla credentials successfully.  Still the same.
Or is my newly created 2fa Tesla account causing this problem? 
Any suggestions?
Thanks for your help.

**Comment by itsMeDavidV** [comment]
Hi @Paddysh with the release of Watchla 2.0 Sign in with Authla has now been phased out. You can now sign in directly on Watchla's brand new companion iOS app. IMO this makes for a much better experience and it is also much more reliable. Just update to Watchla 2.0 and you'll be good to go!

**Comment by Paddysh** [comment]
Hi David
Thanks for your quick response.
Unfortunately the iOS App is not there in the iPhone App Store. The buy button is greyed out. That means, I’m not able to sign in there, which would be much more convenient and reliable, indeed.

![2E34096E-EC90-4938-8FC8-9A1D7EF1B0DC](https://user-images.githubusercontent.com/98241089/150671672-5dd1cbe1-63e6-4739-91dc-f768ce73f104.jpeg)

**Comment by itsMeDavidV** [comment]
Hi @Paddysh thats very weird. Have you tried again since the time of your screenshot? Since Watchla v2.0 adds an iOS companion app, I'm thinking that could throw things off for your download. All though I am seeing in recent days that thousands of pre 2.0 users were able to successfully update without any issues. 

I would try deleting the old Watchla app off of your Apple Watch and then coming back to the App Store on your iOS device and trying again.  If that doesn't work, I'd recommend reaching out to Apple Support as this seems to be an issue they would be proficient in solving.
