### ISSUE TITLE
iOS app download button says "purchased" and is grayed out

### ISSUE THREAD

**Issue by Paddysh** [itsMeDavidV/Watchla-Support#23]
Hi David
Thanks for your quick response.
Unfortunately the iOS App is not there in the iPhone App Store. The buy button is greyed out. That means, I’m not able to sign in there, which would be much more convenient and reliable, indeed.

![2E34096E-EC90-4938-8FC8-9A1D7EF1B0DC](https://user-images.githubusercontent.com/98241089/150671672-5dd1cbe1-63e6-4739-91dc-f768ce73f104.jpeg)

_Originally posted by @Paddysh in https://github.com/itsMeDavidV/Watchla-Support/issues/22#issuecomment-1019442837_

**Comment by itsMeDavidV** [comment]
Hi @Paddysh thats very weird. Have you tried again since the time of your screenshot? Since Watchla v2.0 adds an iOS companion app, I'm thinking that could throw things off for your download. All though I am seeing in recent days that thousands of pre 2.0 users were able to successfully update without any issues.

I would try deleting the old Watchla app off of your Apple Watch and then coming back to the App Store on your iOS device and trying again. If that doesn't work, I'd recommend reaching out to Apple Support as this seems to be an issue they would be proficient in solving.

**Comment by JeroenKettenis** [comment]
Same here. 
i can re-install the Watchla app directly on the watch, but not on iOS. But the latter is required now to be able to sign in.

P.s.: The FAQ is not up-to-date, it only mentions that Watchla is a pure watch app only.

**Comment by itsMeDavidV** [comment]
@JeroenKettenis when you re-install the watch app on your watch, which version do you get 1.95 or 2.0? You can check her version number in preferences. 

It's unfortunate this is happening as this is out of Watchla's control. I'll try my best to re-produce this issue and see if I can find a remedy.

Also, FAQs are being updated tonight.

**Comment by JeroenKettenis** [comment]
Hi David,

It is version 2.0.

**Comment by itsMeDavidV** [comment]
Quick update: 

FAQs were updated to reflect 2.0 and more Qs are continually being added.

Still working on this issue.

**Comment by itsMeDavidV** [comment]
@Paddysh  @JeroenKettenis 

Just wanted to check to see if this issue is still occurring for you both?

If so, can you try deleting the Watchla app from your Apple Watch and then try to download the iOS app first?

**Comment by JeroenKettenis** [comment]
Hi David,

I still have the issue.
I uninstalled Watchla from my watch. Then still in the App store is has the greyed-out purchased button. Also uninstalling Authla did not help.


 
 
With kind regards,
 
Jeroen Kettenis

**Comment by itsMeDavidV** [comment]
@JeroenKettenis ok send me your email here: https://watchla.app/contact and I'll add you into the beta. From there you will be able to download both Watchla iOS and WatchOS apps via TestFlight. Sorry for the inconvenience.

**Comment by Paddysh** [comment]
Hi David
Same here. I’ve deleted and reinstalled on the watch several times. Watchla on the iOS AppStore is still greyed out. Even after iOS upgrade.
Thanks for all your support.
Patrick

**Comment by itsMeDavidV** [comment]
@Paddysh sorry to hear that. PM me your email here: https://watchla.app/contact and I'll add you into the beta as well.

**Comment by itsMeDavidV** [comment]
@JeroenKettenis  @JeroenKettenis I have had TestFlight invites to the beta sent to both of your emails. Just follow the steps in the email and you'll be able to download Watchla via TestFlight.

**Comment by JeroenKettenis** [comment]
Hi David,

The Testflight version works great!
Thanks.


 
 
With kind regards,
 
Jeroen Kettenis

**Comment by itsMeDavidV** [comment]
@JeroenKettenis glad to hear that! You're very welcome

**Comment by Paddysh** [comment]
Hi David
Now it works perfectly. 
I’m  just wondering what happens when the test flight Version expires.
Anyway, many thanks for your efforts.
Patrick

**Comment by itsMeDavidV** [comment]
@Paddysh sweet!

The beta is updated regularly so no worries there. You actually kinda lucked out, because a really awesome feature is coming to beta next week! I don't want to reveal just yet, but it will easily be one of the top features on Watchla when it makes it on to the public App Store version.

Also @Paddysh  @JeroenKettenis the current beta version is the same as the current App Store version, so if Watchla is working nicely for you, feel free to leave a review, as reviews really help the app grow :)

**Comment by abrister77** [comment]
I am having this exact issue and have also tried deleting off the watch but ios app store just says purchased

**Comment by itsMeDavidV** [comment]
@abrister77 sorry to hear that. Just like mentioned above if you send me your email here: https://watchla.app/contact I'll get you into the beta as well so you can download Watchla

**Comment by itsMeDavidV** [comment]
Note to all after the time of this comment: unfortunately I cannot manually add every user that encounters this issue to the beta.

At its core, this is an Apple issue--not a Watchla issue. 

I'm doing my best to see if I can find a recommended solution for the few users that experience this issue and when I have a good verified solution, I will post it to https://watchla.app/faqs/ and here as well. 

In the meantime, if you encounter this issue please contact Apple Support as they are best equipped to handle this situation for you. 

If any of you have solved this issue, please do let us know in this thread.

Thanks!

**Comment by dabenv** [comment]
Meet same issue, but finally I have my download button back after I deleted Watchla WatchOS app for 1 or 2 days, I think mostly apple purchasing service issue...

**Comment by itsMeDavidV** [comment]
@dabenv glad to hear of this. I wonder if there is a way to clear the cache manually to satisfy the App Store. Maybe by deleting watch app and then restarting..

**Comment by itsMeDavidV** [comment]
Given that there have been no more reports of this as of late, I'm going to close this. If anyone still experiences this issue, please comment on this thread and I'll re-open.

I'm going to assume this was a WatchOS related bug related to the transition from watch only app to watch companioned app. This transition happened back in version 2.0 some time ago and the overwhelming majority have successfully made the transition since then.
