### ISSUE TITLE
Can Watchla use by two people

### ISSUE THREAD

**Issue by matkohlk** [itsMeDavidV/Watchla-Support#275]
myself and my wife use Watchla, I am the vehicle owner and I had added her to use the car.  When she set up her Watchla, does she log on to my Tesla account? Or can she just log on to her Tesla account?
So far she log on to her own Tesla account. my Watchla work fine. But her Watchla can open the car door only but does not start the car. 
please help. Thank.

**Comment by itsMeDavidV** [comment]
Hi @matkohlk your wife should be able to use her Tesla account just fine. Just keep in mind as the owner, only you will be able to setup a virtual key, however once setup, she will be able to send commands just like you.

Can you send over her support code via https://watchla.app/contact so that I can investigate and see if there are any obvious issues? Please be sure to reference this issue.

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
