### ISSUE TITLE
No locky after walking away. 

### ISSUE THREAD

**Issue by veitch123** [itsMeDavidV/Watchla-Support#348]
This has happened a bunch of times now and, looking on the Watchla site, I think it's a limitation of the Apple watch perhaps but I wanted to mention it here. 

I can't use the Watchla as a proximity car key because it just doesn't lock when I walk away. I came back to it and the windows were open and the doors unlocked. Not sure what can be done about this or if I'm using it wrong but thought I'd mention it here.

**Comment by itsMeDavidV** [comment]
Hi @veitch123 you're correct, as mentioned in Watchla's FAQs, Passive Entry and Walk-away Lock can sometimes be limited by your Apple Watch's onboard battery management system, so while Watch is capable of both of these, they might not always trigger when the Watchla app is not active and open, because of Apple's limitations on background Bluetooth connectivity in the Apple Watch. 

Of course, were always constantly refining Watchla's Bluetooth connectivity to best adapt to this, but for now this is a limitation. We are seeing that in later versions of WatchOS and newer Apple Watches this limitation is getting more and more relaxed.

Additionally we will be introducing the 2nd version of Watchla's Bluetooth protocol shortly, which should bring Bluetooth performance improvements across the board to Watchla, including in this area.
