### ISSUE TITLE
App won’t work stand alone even though WiFi and cellular.

### ISSUE THREAD

**Issue by zwenkie** [itsMeDavidV/Watchla-Support#380]
It is said the watch app will work stand alone. However, when my phone is set to flight mode the app stops working.

**Comment by CassandraMarie** [comment]
Hi @zwenkie, the watch functions independently, meaning you don't need your iPhone with you when using Watchla to control your Tesla. 

We are currently transitioning from the recent API change and focusing on addressing the immediate issues. However, we are actively working on enhancing Watchla, and this feature will be available in the future.

**Comment by CassandraMarie** [comment]
Hi @zwenkie, In order to communicate with your Vehicle over the internet Watchla needs to have a reliable connection to the internet. Either a paired device, Wifi connection, or cellular connection. Watchla can also communicate independently with the vehicle via Bluetooth as long as Watch Key is set up in the watch app.

**Comment by CassandraMarie** [comment]
As we haven't received a response for some time, we will be closing this issue. If the problem continues or arises again, please feel free to reopen the issue or reach out for more help.
