### ISSUE TITLE
Feature request : add wake option for XXX minutes

### ISSUE THREAD

**Issue by user858753257** [itsMeDavidV/Watchla-Support#41]
Hey , 

I'm searching for a way to wake up my M3 for a period of time .
Could be an iOS Shortcut which I can configure (eg. 20min) 

I'm using TeslaUSB and I don't want to run sentry mode all night only to power one USB sync :)

**Comment by itsMeDavidV** [comment]
@F3000 Not super familiar with TeslaUSB but to my knowledge sentry mode actually doesn't keep the vehicle awake, it just keeps the vehicle from going into deep sleep. That's why waking is much faster when sentry is active. 

Other than outright waking the vehicle every 60 seconds or so, there is no standard way to keep the vehicle awake other than physically being in the car or leaving the door open.

There is functionality to customize Wake settings in the Tesla BLE api however we're not quite there yet for Watchla ;)

Unfortunately most people want to wake their cars as least as possible so there might not be too much demand for a keep awake feature
