### ISSUE TITLE
Watch complication in Miles not KM

### ISSUE THREAD

**Issue by mosesvii** [itsMeDavidV/Watchla-Support#44]

**Comment by mosesvii** [comment]
While in the watch app the distance is showing in KM remaining. The complication however is showing Miles remaining. 
the name of the car is also not being pulled. It simply says ‘Vehicle Name’ on the watch face.

**Comment by itsMeDavidV** [comment]
Hi @mosesvii thanks for reporting this. Are the actual data values still being shown? 

Also can you send me your Watchla support code here: https://watchla.app/contact so I can take a look at any error logs you might have and see if there are discrepancies.

**Comment by ddauw** [comment]
I have a similar issue, one complication is showing Miles and another is showing KM, in my case it should both show KM.


![Range](https://user-images.githubusercontent.com/96821582/160637243-b6f554f1-5a9d-4709-8124-06cee556a29e.jpg)

**Comment by itsMeDavidV** [comment]
@ddauw assuming you took these 2 screenshots at around the same time, the 200 mi one seems to have gotten placeholder data. Meaning it has not yet attributed car data to the complications. This could be for a range of reasons--the most common being that either the complication was just added or the Apple Watch was just turned on/restarted. Not excluding other possible reasons. I'm not sure of the context before this, but it does seem like that Watchla (in the case of the second pic) has not yet delegated complication data. This would explain the incorrect value (which is also a default placeholder value) and the default miles unit being displayed. In the case that a vehicle data error occurred, you would either see old data presented or 0 km presented.

Is this issue still occurring? and If so have you opened Watchla since the time of the second screenshot? Looking forward to hearing back!

**Comment by mosesvii** [comment]
I've just tested my watch face again, I hadn't been back to it since I posted the issue. 
Happy to confirm it is indeed working well and showing km for both the complication and the face. 
As you suggest, it must have just taken a little while to reconcile when I first installed.

**Comment by mosesvii** [comment]
Happy to close the ticket unless  DDAUW still has issues.

**Comment by ddauw** [comment]
> @ddauw assuming you took these 2 screenshots at around the same time, the 200 mi one seems to have gotten placeholder data. Meaning it has not yet attributed car data to the complications. This could be for a range of reasons--the most common being that either the complication was just added or the Apple Watch was just turned on/restarted. Not excluding other possible reasons. I'm not sure of the context before this, but it does seem like that Watchla (in the case of the second pic) has not yet delegated complication data. This would explain the incorrect value (which is also a default placeholder value) and the default miles unit being displayed. In the case that a vehicle data error occurred, you would either see old data presented or 0 km presented.
> 
> Is this issue still occurring? and If so have you opened Watchla since the time of the second screenshot? Looking forward to hearing back!

Hi,

yes reinstalled everything and now it's working fine. Thanks.

**Comment by itsMeDavidV** [comment]
@mosesvii @ddauw  That's great to hear! Please don't hesitate to re-open this issue should the issue arise again.
