### ISSUE TITLE
Not able to switch vehicles

### ISSUE THREAD

**Issue by normanmaurer** [itsMeDavidV/Watchla-Support#48]
I have multiple teslas and whenever I try to switch to another one it just keeps on trying to fetch the data but never completes.

**Comment by itsMeDavidV** [comment]
Hi @normanmaurer thanks for reporting this. This issues is the  result of a new bug that stems from the new auth flow that was just implemented (see issue #46).

A fix is being created and will be included in the next update of Watchla.

For a now a work around is to sign out and then back in. 

I will update this thread when this bug is fixed.

Also you can select a vehicle from both the watch app and iOS app. So if one is not working you can choose a vehicle on the other.

**Comment by itsMeDavidV** [comment]
Hi @normanmaurer last week Watchla was updated on the App Store and this issue was fixed. To get the fix, just update to the latest version of Watchla.

If this issue still persists for you, please feel free to re-open this issue.
