### ISSUE TITLE
Error Getting Vehicle Data {endless loop}

### ISSUE THREAD

**Issue by KurtSanders** [itsMeDavidV/Watchla-Support#5]
The Watchla app goes into an endless loop displaying the "Error getting vehicle data' and 'Okay' & 'Cancel' do not appear to have any function to end the endless loop.  My preferences are all set to the 'default' for Wake Settings.  Stopping the Watchla App and restarting it (Press the side button on the Apple Watch one time. Then, scroll through the active apps with your finger or the digital crown. Finally, swipe the Watchla app from right to left and tap the large red X to close it.) corrects this looping error, but after a period of time, this same endless loop re-appears. 

https://user-images.githubusercontent.com/12133562/114441999-0d93f000-9b9a-11eb-819b-a260286ebd79.mp4

**Comment by itsMeDavidV** [comment]
Hi Kurt! @KurtSanders 

So this endless loop is definitely a new bug, thanks for reporting it.

I'm curious as to the steps to reproduction for this issue. Is there anything special that happens or specific action that you perform right before this horrible loop occurs? Or is it just a matter of opening the app and the loop automatically starts?

Also I mentioned this in #4 but in case you didn't see it, I'd love to get you into the beta! If you're up for it, send me your email to david@villegasventures.co and I'll have an invite sent out to you.

**Comment by BJMckechnie** [comment]
I'm the same, the green circle scrolls around. Won't connect connects 1 in 25 attempts. Really annoying.

**Comment by itsMeDavidV** [comment]
@BJMckechnie you are most likely facing issue #6 I am working hard to bring a fix to the App Store as soon as possible.

**Comment by itsMeDavidV** [comment]
This particular bug has been identified and a fix is in the works. Most likely, the fix will be included in v1.60

**Comment by BJMckechnie** [comment]
Thanks, how do I subscribe to the issue?

**Comment by itsMeDavidV** [comment]
@BJMckechnie If you're viewing this on your phone, swipe up the comment tab, scroll all the way down and select "Subscribe".

If you're viewing this on Desktop, look to the right tool bar, scroll down and click "Subscribe"

**Comment by KurtSanders** [comment]
How are we to confirm the current version of the Watchla installed?  I checked for the version on the app and on the watch and did not see a version indicated.  Thanks @itsMeDavidV

**Comment by KurtSanders** [comment]
@itsMeDavidV 

On the latest version of Watchla, at 6:23 EDST 4/15/2021, I still get a 'Status Code 408' error when checking the 'P' status on Watchla app.  After pressing the 'Try Again' button that is displayed along with the status code, Watchla does connect and display the status icons.

**Comment by itsMeDavidV** [comment]
Hi @KurtSanders,

Thanks for this feedback!

It looks like you are on version 1.60. However, you pose a good question. I checked myself and there is no way via the App Store to see the current version of a Watch app. You can only verify that you are on the latest version by going to the App Store page of the app and checking to see if the download button says "Open" or "Update". So in light of that I will be adding the version and build number to Watchla's preferences screen in the very next update of Watchla. Thanks for bringing this up.

Also this error in particular (screenshot 1) showed a 408 status code which means that Watchla did successfully send a request to the Tesla API, BUT when Tesla Servers tried to communicate with your vehicle, your vehicle took too long to respond, so as a result the Tesla API threw a 408 status code to Watchla. I recently installed retry protocols into Watchla, so you would only be getting this error after multiple attempts to reach your vehicle (& mult 408's were received).

This is pretty normal to have a 408 thrown when requesting vehicle data, for a number of reasons. Your vehicle could be offline or in deep sleep, it could be having internet connection issues (eg: low LTE reception -> slow internet), or it could be regularly asleep.

If it's the latter, then its definitely the result of a Watchla flaw in the way Watchla wakes and then subsequently requests data from the vehicle. However, I suspect this is not the case as error logging data proves otherwise.

If its the second reason, then there may still be something that Watchla can do like increasing timeout limits for vehicle that Watchla deems to be historically slow to respond. This may be an avenue to pursue.

However, I think it's probably the 1st issue, based on the fact that after the error you say everything was working normally. Sometimes Teslas do take a long time to wake up and respond to the Tesla API after a long deep sleep (just like humans!), but after they do initially connect they are back to normal response times. 

Also you say this happens after tapping the "P" complication. Does this happen every time after tapping the "P" complication or just the first time? Also did you try to reproduce this after the vehicle connected normally and if so did it still throw an error?

**Comment by itsMeDavidV** [comment]
@KurtSanders Also I want to ask if at all have you been faced with the error loop in this new version of Watchla, like in your first video on this thread? Since before the time that you reported it, there have been specific measures in place in Watchla's code base to prevent this specific loop, so it's very hard to reach a state where that error loop would occur on Watchla and thus reproducing it is naturally also hard. Clearly you were able to do it and if it's still happening, I would very much like to know any detailed steps to reproduction if you have any? Thanks gain for reporting this and your very helpful feedback.

-David

**Comment by KurtSanders** [comment]
Dear @itsMeDavidV 

Thanks for your quick response.   I just tired Watchla from the watch's main complication (the 'P' Parked) icon and it immediately generated an 408 error 👎.  The good news is that you have eliminated the endless loop 👍  (Yea, nice work) in the app, but the app does end up presenting two info screens that need to be navigated/acknowledged to resolve the 408 condition, wake up the sleeping Tesla, and get actual Tesla status.

I think you are totally correct in that my Tesla is in a deep sleep.  Having the watch send a command & wait for a wakeup duration may be limited by what Apple allows for an API timeout/retry to the Tesla API website.  When I used the Stats iPhone app, which has a companion watch app, it seemed to wait for the Tesla to wakeup from a deep sleep without a timeout, but then again, I think the Stats watch app was sending the API command request to the nearby iPhone app which did the communication with Tesla API website.  Perhaps the iPhone has longer API timeout allowance than the watch's API's?.  

Lastly, the Tesla app on the iPhone also seems to wait for the Tesla to "wake up", and generates a status message stating that car is waking up.  Is their a "wakeup command" that can wake up the Tesla in a deep sleep or return a status code if it is awake, and them you could follow up with getting the car status with a second command?

#### Again, your Watchla watch app is functioning and the 408 error is understandable.  Ideally, it would be great to trap/catch the 408, wait for 1 sec, and resubmit the same command for car status...  

![IMG_9545](https://user-images.githubusercontent.com/12133562/114938360-06c0e380-9e0d-11eb-91d9-1189e316c595.jpg)
![IMG_9546](https://user-images.githubusercontent.com/12133562/114938368-09233d80-9e0d-11eb-836f-5eedc47ac211.jpg)
![IMG_9548](https://user-images.githubusercontent.com/12133562/114938370-0aed0100-9e0d-11eb-8e2d-99e1e3ff5ca8.jpg)

**Comment by KurtSanders** [comment]
@itsMeDavidV,

On the beta version, I'm still getting the 408 error and the Watchla app loops about 7-10 times with the Error & Try Again Screen before eventually successfully waking up the Tesla and getting status.  

I'm wondering if you can just increase the timeout/retry attempts when receiving a 408 and the API returns no data because the Tesla is in a deep sleep.  I realize that this could also happen when the Tesla is not on the Internet, but then it could just display a error message after the timeout and no data period has elapsed...

**Comment by itsMeDavidV** [comment]
Hey @KurtSanders quick update (will respond in detail later) just wanted to let you know that something like the method you mentioned (eg: timeout -> wait x seconds -> retry) is currently being implemented into the next App Store version of Watchla. I think it's a good idea and it most likely will remove the necessity for the error alert on first data load.

A similar practice is used by Watchla when waking the vehicle and it works wonders!

**Comment by KurtSanders** [comment]
That will great to test and I'm confident that n number of retries (where n > 1) will work.  Perhaps a user setting so that one can increase the number of wait/retires before indicating that the vehicle is unavailable.

**Comment by KurtSanders** [comment]
@itsMeDavidV 

I'm on Watchla version 1.70 (65) and still experiencing the two error screens when the Tesla in in a deep sleep.  It requires several (about 4-5 loops) of pressing the acknowledgment screens of the "Error try again" prompts before it finally resolves and obtains Tesla status.

When the Tesla is not in a deep sleep, the Watchla App obtains status as expected.  I do notice that Watchla does not update the watch's complication icon from the sentry mode icon for quite sometime after driving the car.  It does update if I press the sentry mode icon, but takes me to the Sentry mode screen which I have to cancel to get a refreshed update.  It might be better if Watchla would check status if it has been x mins since last update to insure that Sentry mode is still active rather than display Sentry mode screen which one has to cancel to get car status screen.

**Comment by itsMeDavidV** [comment]
@KurtSanders that's really good to know I will increase max num of retries & possibly time intervals between them in build 66.

And Watchla complication updates are on a set schedule (with Wake settings turned off updates occur about 4-5 times/hour), just because Apple limits the max amount of times that you can:
1) update complications
2) operate in background

This is due to battery management in WatchOS and unfortunately there is no way around this. BUT I'm going to be doing a bit of optimizing. Main goal is for Watchla to update more frequently during action hours and less frequently during dormant hours. This will be on a learning basis so that its based on ones interactions with ones cars and not necessarily standard time of day. eg: if someone usually leaves for work at 2:30 AM every weekday, Watchla will know to start updating more frequently at 1:30 AM on weekdays.

Approximately how long did it take for the Sentry Mode complication to update, would you say?

**Comment by KurtSanders** [comment]
@itsMeDavidV 

Those planned changes look promising and I like the smart polling.  

Thanks for reminding me the parameters that the Apple Watch enforces on polling apps for sake of battery optimization.    The Watchla icon on the watch's main complication updates usually after a 4-5 minutes which makes perfect sense given the polling frequency.  If I want to update it before this, I just press on the icon.

Again, keep up the great development.

**Comment by KurtSanders** [comment]
Dear @itsMeDavidV,

I installed beta version 1.70 and refreshed authentication token using the Authla app.  Watchla is functioning as expected and did not present an error screen on first use obtaining car status.  That's a great sign!   

I will report back tomorrow with frequent testing...

Thanks for working on the improvements!

**Comment by KurtSanders** [comment]
@itsMeDavidV 

Does the car information being displayed always get refreshed when I press on the watch's complication icon for details? If not, another low priority request would be to indicate the 'last update date/time' perhaps somewhere on the main status icon screen or in the Watchla's preferences next to version info so one can tell how accurate the car information being displayed is.  Great app!

**Comment by KurtSanders** [comment]
@itsMeDavidV 

Great update and fix.  I am going to close this issue as Watchla version 1.70 (67) is working as expected to get the car status when in a deep sleep! 🥇

**Comment by BJMckechnie** [comment]
Sorry do we have to do anything our end or download any update? If so how?

Kind Regards
Barry Mckechnie

**Comment by itsMeDavidV** [comment]
Hey @KurtSanders please forgive my late reply! I've been bouncing between different projects this past week so replying to emails and GitHub has been a little sporadic on my part lately. Sorry about that!

So to answer your question about last update labeling I'm definitely open to that. I will also be introducing visual indicators for when a data point is not up to date, so eg: Watchla failed to receive a response from vehicle in last x minutes -> range value indicator opacity drops to 0.5. Once updated it will go back to 1.0.

And I'm so happy to hear that build 67 was an efficient fix! Many thanks to you for providing great, timely feedback along the way! It's extremely appreciated and it was a huge help.

I will continue to update you. 

Build 68 is being worked on now, I'm packing in some added features for Watchla, addressing issue #8 and planning some other fixes. Please do let me know if you think anything should be added to the line up, as build 68 will most likely be released on the App Store!

**Comment by itsMeDavidV** [comment]
Hi @BJMckechnie so I'm happy to tell you that this issue is fixed in version 1.70. Version 1.70 will be out on the App Store in a couple of days and once it's out you will be able to update. There is just one last beta build left before it's introduced to the App Store!

The specific version that @KurtSanders is referencing is currently only available in beta. But like I said above it will be available on the App Store shortly!

**Comment by BJMckechnie** [comment]
Hello,
I keep checking the App Store and all I see is that I have purchased Watchla and the button is greyed out...Nothing happens or shows to install a new version. 

Any thoughts?

Kind Regards
Barry Mckechnie

**Comment by itsMeDavidV** [comment]
@BJMckechnie Often times the App Store on the iPhone is not reliable for downloading/updating Watch apps. I recommend updating from the App Store app on your Apple Watch itself, that should work reliably. Also since version 1.70 (I believe) you should be able to check the current version of Watchla that is installed by going into Watchla's "Preferences" screen & scrolling all the way down.

**Comment by KurtSanders** [comment]
Dear David,

I am legacy Watchla user and noticed that when I access Watchla from iOS
TestFlight I get prompted for a subscription plan.  The watchla on my apple
watch still seems to work, but will it stop working if I do not choose a
subscription?

I noticed on AppStore, legacy users are still supported.

**Comment by itsMeDavidV** [comment]
Hi @KurtSanders sorry to hear this. To answer your question, your Apple Watch app will most likely continue to stay signed in (if not please let me know). It sounds like all you may need to do is force close your Watchla iOS app and re-open it as Watchla could not register your original App Store transaction.

Can you reply with a screenshot of your your support screen on the Watchla app? It should have a version on there and possibly a data that would help in our efforts to investigate.

**Comment by KurtSanders** [comment]
﻿Dear David,Watchla on the Apple Watch signed out and the support code is 9dTFWSCOV7.  ¸¸.•*¨*•*´¨)¸.•´¸.•*´¨) ¸.•*¨)(¸.•´ (¸.•` ¤ Kurt Sanders2485 Ridge RoadXenia, Ohio 45385+1 (937) 723-0010On Feb 16, 2025, at 9:07 PM, David Villegas ***@***.***> wrote:﻿
  Hi @KurtSanders sorry to hear this. To answer your question, your Apple Watch app will most likely continue to stay signed in (if not please let me know). It sounds like all you may need to do is force close your Watchla iOS app and re-open it as Watchla could not register your original App Store transaction.
Can you reply with a screenshot of your your support screen on the Watchla app? It should have a version on there and possibly a data that would help in our efforts to investigate.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



itsMeDavidV left a comment (itsMeDavidV/Watchla-Support#5)
Hi @KurtSanders sorry to hear this. To answer your question, your Apple Watch app will most likely continue to stay signed in (if not please let me know). It sounds like all you may need to do is force close your Watchla iOS app and re-open it as Watchla could not register your original App Store transaction.
Can you reply with a screenshot of your your support screen on the Watchla app? It should have a version on there and possibly a data that would help in our efforts to investigate.

**Comment by itsMeDavidV** [comment]
Hi Kurt we released version 4.3.1 last night which should fix your issue.

If you still are prompted to sign in with email or Apple, sign in goto the subscription screen and then tap cancel at the very bottom. Then choose an option and you should be redirected to the sign in with Tesla option.

**Comment by itsMeDavidV** [comment]
Hi @KurtSanders, additionally if v4.3.1 does not fix this issue automatically for you, try deleting and re-installing Watchla. If that does not work, we have version 4.3.2 set to be released in the coming hours which should fix this issue for you automatically.

**Comment by KurtSanders** [comment]
Thanks for your support David, version 4.3.1 I re-downloaded allow me to authenticate to Tesla and it is working….   I am a TestFlight user, but hesitant to try 4.3.2 since it might be that TestFlight is causing the previous legacy issues?¸¸.•*¨*•*´¨)¸.•´¸.•*´¨) ¸.•*¨)(¸.•´ (¸.•` ¤ Kurt Sanders2485 Ridge RoadXenia, Ohio 45385+1 (937) 723-0010On Feb 17, 2025, at 8:32 AM, David Villegas ***@***.***> wrote:﻿
  Hi Kurt we released version 4.3.1 last night which should fix your issue.
If you still are prompted to sign in with email or Apple, sign in goto the subscription screen and then tap cancel at the very bottom. Then choose an option and you should be redirected to the sign in with Tesla option.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>



itsMeDavidV left a comment (itsMeDavidV/Watchla-Support#5)
Hi Kurt we released version 4.3.1 last night which should fix your issue.
If you still are prompted to sign in with email or Apple, sign in goto the subscription screen and then tap cancel at the very bottom. Then choose an option and you should be redirected to the sign in with Tesla option.

**Comment by itsMeDavidV** [comment]
Hi @KurtSanders good to hear that. V4.3.2 is now available on the App Store as well so no need to proceed with TestFlight if you don't want to!
