### ISSUE TITLE
Confusing Warning Message

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#52]
It is unclear to me whether the Warning about “Do not wake” applies also to “Do not wake in background”. The description for the latter seems to say we can have Watchla gather data from the car without waking it if it's asleep. But the warning leads me to fear that activating “... in background” could cause problems. 
Also unclear: what does “accurate vehicle data interruptions can occur” mean? If such an interruption does occur does it mess up only Watchla, or can it throw things off in Tesla's own data tracking?
Being able to pull Watchla data while asleep seems nice, but the warning makes it seem scary to try to take advantage of that. 

![image](https://user-images.githubusercontent.com/9358980/160882297-9906d15b-7cd3-4c73-a785-f3d29240d717.png)

**Comment by itsMeDavidV** [comment]
This is a feature for those with heightened concerned over phantom drain. Though this group is a small minority, there are enough users who use and have a need for Do Not Wake functionality, that it warrants its existence. I personally do not use this feature and for the best experience Watchla has to offer, I'd recommend not using it. However, different people have different needs and I'm glad those that would like to use this feature have access to it.

In short, Do Not Wake is prone to cause vehicle data disruptions, because your car will not be woken and instead Watchla will have to default to old data when it cannot reach a vehicle that is asleep (which may be inaccurate in the later time that it is shown). If your car is already awake, it can still retrieve data normally.

If you're conscious about phantom drain, I'd recommend using 'Do Not Wake in Background' instead of 'Do Not Wake'. This will allow Watchla to wake your vehicle while the app is open to provide accurate data/reliability when most needed, however it won't wake your vehicle when the app is in background. Therefore complications might not be updated, critical vehicle alerts may not be available, etc.

Do Not Wake functionality from Watchla only prevents Watchla from waking your vehicle. It will not stop another app from waking your vehicle. If you're worried about phantom drain, it's important to remember this as well as disabling Sentry.

**Comment by ttwajsb** [comment]
This answer is better than what I, in the meantime, found on the FAQ page. You might consider blending this with what's there.

I've never had phantom drain issues since I leave my car plugged in every night, so at least when I'm not traveling I'll go back  to turning off both DoNotWake options. Very much appreciate this clarifying insight.

**Comment by itsMeDavidV** [comment]
You're very welcome! I will update the FAQs
