### ISSUE TITLE
My watch never shows correct data

### ISSUE THREAD

**Issue by zeetaher** [itsMeDavidV/Watchla-Support#60]
I’m not happy with this software.  It always shows blank on my watch face.  I’ll have to launch the app to see the data on the widgets.  What’s the point in having widgets if I have to launch the app to activate the data for the widgets

**Comment by itsMeDavidV** [comment]
Hi @zeetaher sorry to hear that. Watchla complications depend on background updates with your car to show correct up-to-date values around every 15 minutes or so (when not in Do Not Wake mode). 

In these background updates, your Apple Watch only gives roughly 15 seconds or so to complete this update due to battery preservation requirements for your Apple Watch. So if your vehicle is slow to wake or connect to the internet, it can often take longer than the allotted 15 seconds for your vehicle to communicate back to Watchla so that Watchla can then update your complications.

Sometimes after a long time of inactivity or when your Tesla is not on Sentry mode it can be very slow to wake, often times taking more than 30 seconds to wake, obviously pushing past the 15 second load time threshold for WatchOS. That's why if you rely on Watchla complications actively through out the day it's a good idea to keep Sentry Mode on.

Alternatively, your vehicle could be having internet connectivity issues which may contribute to longer load times. Sometimes this happens when your car doesn't have good LTE reception or is connected to a weak WiFi signal or is parked in an area that weakens LTE signals, such as parking garages, metal garages, etc.

Lastly, it's a good idea to check your Apple Watch and its paired iOS device for any internet connectivity disruptions or slow connections as that can affect load times as well.

Also If you send over your Watchla support code, I'd also be happy to take a look at any error logs you might have to see if you have faced any extraneous issues that may have caused this disruption. Support codes can be found in the support screen. You can either send it here by replying to this thread or securely here: https://watchla.app/support

I hope this bit of info helps clear up any confusion. Sorry again that this issue has negatively impacted your Watchla experience.

-David

**Comment by itsMeDavidV** [comment]
Hi @zeetaher is this issue still occurring for you?

**Comment by itsMeDavidV** [comment]
Closing this issue since last response was a while ago. If the issue persists, please feel free to re-open and reply to this thread, thanks!
