### ISSUE TITLE
Rebuilding Layout

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#61]
Super annoying to have to rebuild my custom layout every time I have to re-login. Please set up a way to persist the layout, or at least an easy way to save and reuse in a couple taps. Thanks.
Btw, I’m 5,126 miles into my trip and haven’t used it nearly as much as I thought because it always takes so damn long to Wake/Load—and too often just logs out spontaneously. What can you do to hasten and stabilize it? I want to love this.

**Comment by itsMeDavidV** [comment]
Hi @ttwajsb sorry about the long wake/loads. Watchla is still working out the gaps caused by the drastically shorter token expiration times that Tesla recently implemented. Version 2.5 (just released) addresses this in a part 1 of x solution and currently cuts previous wake times by up to 30 seconds. So thats a bit of help. Version 2.6 (still in beta) is very promising and significantly weeds out most gaps in service that lead to long wait times or sign-outs.

If you'd like, I can invite you to the beta so that you can download version 2.6 of Watchla and give feedback on your experience with the new fixes & upgrades. Just send your email here: https://watchla.app/contact and I'll send you a TestFlight invite.

As for the custom layouts resetting, that is the side effect of the problem at hand (currently being addressed). It's supposed to reset to default along with other settings at sign out to provide the next signed in experience with a blank slate. 

You shouldn't be being signed out at all, unless you choose to sign out and therefore settings and custom layout should not reset to default unless you choose to. Once the above mentioned bugs are fixed / gaps filled, this side effect should not occur.

**Comment by itsMeDavidV** [comment]
@ttwajsb also just released v2.6 which should fix a lot of the issues that have led to involuntary sign outs and long load/wake times.

https://apps.apple.com/us/app/watchla/id1546599747

**Comment by itsMeDavidV** [comment]
Hi @ttwajsb are you still experiencing sign out issues in v2.8?

**Comment by ttwajsb** [comment]
Much better lately. Hasn't signed out for several days, and only taking several seconds to wake/load. Starting to get more confident using it. Was able to open my trunk and frunk yesterday by tapping Watch with my nose while my arms were carrying stuff.

**Comment by itsMeDavidV** [comment]
Haha I actually do that all the time. Side note, if you have Hey Siri enabled you can just ask her to do it too. But that's great to hear! Please do let me know if this changes. Performance updates are still rolling out, there should be more sometime next week.

**Comment by ttwajsb** [comment]
No idea how/why, but Watchla signed out again and now I have to rebuild my Custom Layout. Is there no way you can instruct the system to save across logout/login the most recently configured layout? 

Only if not, might there be a way to re-use/move a command? As-is, in order to move the Trunk from [default] bottom right to [my preferred] upper right I must change the bottom right first from Trunk to something else (I use Sentry as the placeholder) so that Trunk is then available to place in upper right. 

Since I always want RemoteStart|Frunk|Trunk / Lock|Climate, and since that differs by three buttons from the default, I must go thru that placeholder process three times whenever I have to re-customize. That's candidly very annoying. I'm hopeful something can be done. Maybe when you tap a grayed-out (ie, already-in-use) button on the list a dialog appears asking if you want to move that button to this new position?

Thanks, as always, David, for listening. This tool has lots of potential, some of it already very gratifyingly realized.
Troy

PS - Spelling error on the Wake Settings iOS page under "Do not wake in background". Says "loads re**al**ted to" where you wanted "loads re**la**ted to".

**Comment by itsMeDavidV** [comment]
@ttwajsb Sorry to hear that. Would you mind sending over your support code so I can see why you were unjustly signed out?

I'll be sure to add the ability to recover a custom layout. So basically, when you sign in again it will ask you something like "Do you want to recover the previously customized layout or revert to default?" 

Also you bring up a good point about the customization process itself, I will definitely see where improvements can be made and try to make it a bit easier.

Also sidenote: thanks for the catch on the typo I will be sure to fix that ASAP.

As always, thank you for your feedback. It really helps a ton.

**Comment by ttwajsb** [comment]
Support code: PIaoo3rP1P
Also, when I couldn't use RemoteStart shortly ago I signed out and back in. After doing so (and rebuilding my layout) I tried RemoteStart again and it went into a blinking talking-to-vehicle condition, then asked for my password. It's unclear whether that's the PIN-to-drive or the Tesla password. After using PIN a couple times because that's what seemed sensible to me I got frozen out of my Tesla account and had to go there to get a new password for Tesla. I came back into Watchla to try again and this time used the Tesla password, which was a total pain because I could not paste into the password field either on my Watch or in the iOS app. Therefore I had to laboriously manually enter a 15-character password (thankfully via the iOS keyboard input function). However, even after doing so the RemoteStart would not work. Gotta say, this is exceedingly frustrating. I've now spent the last half hour just trying to use RemoteStart, and still can't.
Just tried again and got Remote start unauthorized...
Car and phone are both on same good-signal wireless.
I don't recall ever before having had to enter password for remote start. I've used it for months very happily, and certainly never [more than once??] had to go thru the grief if manually entering the password. Is that going to remain necessary? 
What can we do to make this work? 
Thanks.
Troy

**Comment by ttwajsb** [comment]
PS - Sorry to be grumpy. Hadn't realized how much I'd already started depending on Watchla until it wouldn't work. :/

**Comment by itsMeDavidV** [comment]
@ttwajsb no worries,

So passwords for remote start are unfortunately necessary at least once every sign in, here's why:

Passwords for remote start are mandated by Tesla when using RS via the Tesla API for good reason. If someone wrongfully gains access to your Tesla via a Tesla token, they will in no circumstances be able to drive away without also knowing your password.

Tesla is able to access the user's password at anytime without the user's consent (hence why there is no password prompt on the Tesla app for RS), but Watchla cannot do this and rightfully so. 

Moreover, Watchla intentionally removes itself from the sign in process, because I firmly believe Watchla or any other 3rd party Tesla app should **NOT** be able to see or process any Tesla user's account credentials. Therefore there is also no way to save your password for future use at sign in.

At every sign out your password for remote start is completely erased from Watchla.

I know entering your password for remote start can be a pain, but unfortunately, due to security reasons and Tesla's preferred configuration around remote start, there is no alternative.

I'll definitely audit the wording around the password prompt though to see if there is anywhere confusion can be eliminated.

**Comment by itsMeDavidV** [comment]
@ttwajsb Also will take a look at your error logs to see why you keep getting forced signed out and get back to you.

**Comment by ttwajsb** [comment]
Is it essential that the password for Remote Start be entered on the Watch itself? Why can't that be confirmed in the iOS app? I understand that I'm required by Tesla to confirm authority to use RS, but don't understand why that credential check can't be performed just as securely in the app, then setting a flag to tell the Watch that it's cleared to operate. 

If it has to be on the Watch, would it be possible to enable pasting into the password field? It is highly tedious to enter a 15-mixed-character password using only the touch/drag interface on the Watch. Could a keyboard be added, at the very least?

Another option: confirm just the PIN-to-drive instead of the password. The former is already approved by Tesla to allow starting the car.

**Comment by itsMeDavidV** [comment]
@ttwajsb Added the ability to recover a previous layout eliminating the need to re-make one. Thanks for the feedback/inspiration that led to this!
 
![image](https://user-images.githubusercontent.com/12491192/172673087-c8a0bb1c-603c-4088-86be-84de2ced3c00.png)

**Comment by itsMeDavidV** [comment]
@ttwajsb Unfortunately pin to drive has almost no affect remotely, it's mainly a security feature in the vehicle itself. Tesla doesn't offer pin to drive verification for RS. That would be awesome though!

As for password entry you can always enter the password on your phone and it will reflect in the textfield on your watch--if this is not the case for you, please do let me know.

Watchla's watch app and iOS app have separate, local keychains so transferring passwords between them is not ideal/as secure.

V3 will have a giant feature addition that will eliminate the need for password verification for RS in most cases. Can't speak on this just yet--but it will come out soon enough.

**Comment by ttwajsb** [comment]
Thanks for the Twitter shout-out, David.

Something's more stable these days as I've not had to re-login for at least a couple weeks. I have, though, encountered a situation I'll try to describe.

I tap Remote Start icon and it displays this screen: https://share.icloud.com/photos/049eGFFpzRlzglw6EyMIDP9xA

Thankfully at least, when I simply open the iPhone app the Watch then catches on and starts working as intended— _without_ having to authenticate on the iPhone again, notwithstanding the message on that screenshot says I'll have to. But I do wish this step didn't slow me down.

**Comment by itsMeDavidV** [comment]
You're welcome!

Thanks for sharing this, definitely shouldn't be happening--I'll take a look.

**Comment by ttwajsb** [comment]
Hey, just encountered the new Recover Previous Layout feature  for the first time and it worked great! Thanks SO much for implementing that.

**Comment by itsMeDavidV** [comment]
@ttwajsb That's awesome! Im glad to hear that. 

Sorry if you were possibly unintentionally signed out again? If so, can you send over your support code so I can have a look at any sign out errors that took place? -> https://watchla.app/contact

**Comment by ttwajsb** [comment]
PIaoo3rP1P

Yeh, I've actually been experiencing sign-in issues the last few days, and the Watch has been really slow about connecting, and fairly often refusing to do so at all.

**Comment by ttwajsb** [comment]
Rebuild layout worked again, but shouldn't have needed it. Used Watchla to go for coffee earlier, and when I went back to the car afterwards to go home the app had logged out spontaneously.
