### ISSUE TITLE
Open/unlock/close charge port complication does not work

### ISSUE THREAD

**Issue by marckessels** [itsMeDavidV/Watchla-Support#63]
When using the Open/unlock/close charge port complication in the modular watch face, watchla opens, wakes up the vehicle, then show “ loading” and at the instant the range is displayed (had to take a slowmotion video to see what it was), the app disappears (crash?). 
when opening the chargeport directly from the watchla app on the watch, it works just fine. 
 Reinstalling the app on phone and watch does not solve the issue.

**Comment by itsMeDavidV** [comment]
Hi @marckessels thanks for reporting this. I'll try to reproduce this issue on my end and get back to you with an update.

**Comment by itsMeDavidV** [comment]
Hi @marckessels sorry for the late reply, it's been a busy week. I was able to reproduce your issue and implement a fix. The fix will be included in the next update of Watchla, which if all goes well, will be tomorrow.

I will keep this issue open until that update with the fix is available on the App Store so that others may see this info as well.

Sorry again for the inconvenience!

**Comment by itsMeDavidV** [comment]
Update: App Store update containing the fix will most likely be released Saturday EST

**Comment by itsMeDavidV** [comment]
@marckessels a new Watchla update (v2.9) with the fix for this issue has just been released to the App Store. 

Thanks again for reporting this!

**Comment by marckessels** [comment]
@itsMeDavidV thanks, just checked (and after a forced update of the app on the watch) it now works as intended! Well done 👍🏻

**Comment by itsMeDavidV** [comment]
@marckessels Thank you! You're very welcome 😊
