### ISSUE TITLE
Apple Watch and "Driving with PIN"

### ISSUE THREAD

**Issue by khbue** [itsMeDavidV/Watchla-Support#64]
When Driving with PIN, you have to enable the car to drive with your PIN. This is true, when using the smartphone. By using the Apple Watch for driving, the car does not require the PIN. You just can drive.
Please change Watchla accordingly.
Greetings from Germany! Karl

**Comment by itsMeDavidV** [comment]
@khbue Hi Karl, 

Assuming you're referring to the official Tesla app, when using Pin  to Drive you actually don't need to enter your pin when engaging in remote start (This could be different in Germany). 

Furthermore, the Tesla API doesn't need or request pin verification to initiate Remote Start.

If this is not the case in your region please do send a video so I can better understand from your POV.

-David

**Comment by ttwajsb** [comment]
I would not want to have to enter a PIN on my Watch in order to activate Remote Start. The whole point of doing so from my Watch is the convenience of not doing so on the car screen, while still having the security of PIN to Drive in the car so that if (when!) I inadvertently leave my phone in my car and walk away, no-one can drive away with both. I've found the status quo to be the ideal condition.

**Comment by khbue** [comment]
Good point!! Since the watch always remains on the wrist, there is no risk, one can drive my car.
Thanks! 

Viele Grüße!  Best regards!


Prof. Dr. Karl-Heinz Büttner

Mobil:  +49 160 7559032
Email:  ***@***.***
