### ISSUE TITLE
Can’t connect app to watch

### ISSUE THREAD

**Issue by Hultmann00** [itsMeDavidV/Watchla-Support#67]
Hey. I can’t connect the watch to the app on the phone. Have tried to uninstall the app but that didn’t work either.

**Comment by itsMeDavidV** [comment]
Hi, sorry to hear that. If you send over your Watchla support code to https://watchla.app/contact I can check out your error logs and see what exactly is causing the communication disruption between the Watchla iOS & watch apps.

However generally watch-to-phone communication issues happen because of pairing issues between the phone and watch.

Some possible steps to take in the mean time: 

- sign out and then back in to Watchla
- check to see that your watch is not experiencing pairing issues--here's a helpful link with more info on that: https://support.apple.com/en-us/HT205025

**Comment by Hultmann00** [comment]
Hi, my support code is iZzXjQb5H2



ons. 13. jul. 2022 kl. 23:21 skrev David Villegas ***@***.***

**Comment by itsMeDavidV** [comment]
Hi @Hultmann00 so after reviewing your error logs it appears you did encounter a few instances where your iOS device did not register that the watch app was installed.

I'd recommend restarting your Apple Watch and iOS device, if all goes well this should reset things back to normal working order. If that does not work, I'd recommend re-pairing your Apple Watch with your iOS device.

Please do keep me updated on the outcome.

**Comment by itsMeDavidV** [comment]
Hi @Hultmann00 its been a while since we last spoke, is this issue still occurring?

**Comment by itsMeDavidV** [comment]
Given that this issue has gone inactive, I'm closing it. If the issue persists, please feel free to re-open it and reply to this thread. Thanks!
