### ISSUE TITLE
Inconsistent Readiness

### ISSUE THREAD

**Issue by ttwajsb** [itsMeDavidV/Watchla-Support#70]
I LOVE Watchla the many times it works well and quickly. I'm baffled about how often it gets stuck. I can use a couple features without delay, then a couple minutes later it's stuck. Here are three instances in the last couple days, each with a slightly different display condition. 

https://share.icloud.com/photos/086voEo1fEnBN9OYOcWNq5_TA

https://share.icloud.com/photos/041Nan9AkxhCgATNKVIDqGCyQ

https://share.icloud.com/photos/00e7FEAn0Ox0HftgX91bIlk3g

**Comment by itsMeDavidV** [comment]
@ttwajsb Thanks for this feedback. Quick question, in the last video did the vehicle ever finish waking? Also was your vehicle connected to WiFi at the time?

**Comment by ttwajsb** [comment]
Sorry but don't recall whether in those instances it eventually connected or I just gave up. I'll pay more attention to that next time and send a follow-up. 

Overall, my unscientific impression is that it works great maybe 60% of the time. 

I've told a couple other Tesla drivers about Watchla in the last two weeks on my road trip (this time Montana) because despite the issues I've faced I have high hopes for them being resolved.

**Comment by itsMeDavidV** [comment]
@ttwajsb Ok so for this specifically:

- Infinite range indicator loading thingy bug has been resolved
- Wake polling on Watchla's side is now double the speed--hopefully this translates to significantly faster wake times

Also in addition to that, I removed the bug that caused involuntary sign outs on the Watch app. You were probably more prone to this bug, because you probably drove through places with less than ideal internet connections along your trip. Essentially what happened is if the app failed to refresh your Tesla token it would sign you out assuming that the token was revoked. However, in most cases it was because of lack of ideal internet connection to make the call to Tesla servers in the first place.

These updates will be going out to the App Store hopefully tomorrow.

Thank you for your patience and support, I really do appreciate it and it helps the app improve immensely. Hopefully these updates will make the initial load times much faster.

I'll keep you posted!

**Comment by itsMeDavidV** [comment]
@ttwajsb happy to report that v2.94 has recently been released to the App Store and I wanted to see if you have updated by chance? And if so how is your experience going so far? Are you seeing shorter wake times / quicker readiness?

**Comment by ttwajsb** [comment]
Sad to say little visible improvement. However, I've been traveling with limited internet so when I get home where is confidently stable I'll be able to gauge whether is better more of the time. Last couple days...

https://share.icloud.com/photos/03cnbzg4b4F-cFlmgqVBZHtFg

https://share.icloud.com/photos/075HplmExmTX4bTr9HO41q0zA

https://share.icloud.com/photos/0fbL6nRC5elUSDUIKeoUScdyQ

https://share.icloud.com/photos/0c63ly4G6uW9hCwxlrQKlFi2Q

**Comment by ttwajsb** [comment]
And yes, this is 2.94 (165)

**Comment by itsMeDavidV** [comment]
@ttwajsb Yeah this does seem to be an internet speed issue. Even with slower wake polling, on a decent connection (for both device and vehicle) it should just be a few seconds. 

In reference to 2nd screenshot, you can have a stronger signal to local cell towers, but the speed itself can vary. This happens a-lot in rural areas. Also keep in mind that your Tesla runs on AT&T cell towers and internet speed to the vehicle is 50% of the equation. 

V3 will help greatly in these types of low internet speed situations. Can't speak on it too much but when v3 beta is ready I can certainly send you an invite.

I'm going to keep this issue open, just so we can track how this issue progresses now vs after the release of v3.

**Comment by Gold931** [comment]
It sounds like I’m having the same issue. I’d say more often than not my commands time out, whether I’m using my watch, or my phone, whether I’m at home on Wi-Fi or out. Sometimes though, it works right after I get the timed out message.

**Comment by itsMeDavidV** [comment]
@Gold931 a lot of this is dependent on the internet speed that your Tesla has. If it's slow on average or it's prone to deep sleep (eg: you routinely keep Sentry Mode off) you will be more likely to experience time-outs since it might take longer for your vehicle to wake and/or relay data back to Tesla servers. 

It might be helpful to go on your Tesla's web browser and do an internet speed test to rule out any slow connection issues.

**Comment by Gold931** [comment]
Thanks. Just turned Sentry mode on, let’s see if that helps.

**Comment by ttwajsb** [comment]
Gotta say, it's still highly variable, and more than half the time frustratingly slow. And it's so inconsistent. I can't figure out when it's gonna be lickety split and when I'll have to wait—and not uncommonly give up. (Are all my attempts visible to you in a log?) I was traveling last weekend and sometimes, boom, right there when I launched; other times, ratso. But at home, at least, I'd sure love for it to always be ready to go.

Here's what I just experienced: https://share.icloud.com/photos/04dCxq4kLPkGQuAUTJ1Mslmzw
Granted, the car had been asleep, but I don't use Sentry Mode in the carport because I have a security camera on all the time.

This was just now my phone's speed where I'm usually standing when I start Watchla on my Watch: https://share.icloud.com/photos/098QhXtT5-fHVQfNooXg29WFA

And this was, also now, the speed (on a different WiFi) where my car sits at home: https://share.icloud.com/photos/036IRnFhrIyukCwAcQWl-SbHA

**Comment by ttwajsb** [comment]
David, this has been almost completely resolved by following the guidance I recommended (in a related case) that you add to your Help content:

“Ensure your VPN service does not auto-connect to trusted networks?” 

@Gold931, I wonder if this would help in your situation as well?
