### ISSUE TITLE
Remote Start not working

### ISSUE THREAD

**Issue by Pdog135** [itsMeDavidV/Watchla-Support#73]
2022 model 3 LR
Remote start has error message after I enter my password from watch. I  entering my Tesla account password. Please advise, it the app broken of is there some other password that has to be set up of added somehow

**Comment by itsMeDavidV** [comment]
Hi @Pdog135 as of the time of this comment, I can confirm Remote Start is working normally in Watchla. You might have entered an incorrect password. It can be kind of cumbersome to enter your password from the watch, so I definitely recommend opting to type it on your paired iOS device, instead.

Also, if you'd like to send your Watchla support code to https://watchla.app/contact/ I can take a look at error logs and see what exactly is causing Remote Start not to work for you.

**Comment by Pdog135** [comment]
I have tried it from using my phone to input the password also like you
suggested, it is still not working.
I have attached my support code

**Comment by itsMeDavidV** [comment]
@Pdog135 Sorry, I can't seem to find your support code from Watchla's contact page? Where did you happen to attach it to?

**Comment by Pdog135** [comment]
I wanted to follow up with you since it has been several days since we last
spoke

**Comment by itsMeDavidV** [comment]
Hi @Pdog135 as I mentioned in my last reply, I didn't seem to receive your support code in Watchla's contact inbox.

Email me your support code directly here: david@watchla.app and I'll get back to you as soon as I can.

Thanks!

**Comment by Pdog135** [comment]
nkt1fPLpEo

Email me your support code directly here: ***@***.*** and I'll get

**Comment by itsMeDavidV** [comment]
Hi @Pdog135 after looking at your error logs, it seems as though on 7 occasions Tesla had blocked you from waking and/or sending commands to your vehicle. This seems to be an isolated incident, nonetheless I am personally getting to the bottom of this to make sure Watchla does everything it can (within its control) to prevent this from happening again.

By chance, did you happen to change passwords, remote log out or anything of that sort around the time this happened? Also did you use a token to sign in to Watchla?

**Comment by Pdog135** [comment]
I did not change anything. The other Tesla functions are working fine. I
used the same password when I logged into the Watchla app
I did not use a token, I just put in my Tesla user name and password

**Comment by itsMeDavidV** [comment]
Ah ok as a test, can you sign out, then sign back in and attempt 2 commands (eg: lock/unlock or flash lights)?

This will help us determine whether this an issue related with your current authorization status or something more persistent.

**Comment by Pdog135** [comment]
I did as you requested and I am getting the same error message

**Comment by itsMeDavidV** [comment]
@Pdog135 ok so that test was actually very helpful. Looking at the logs it seems that after signing out and then back in, this issue on the iOS app corrected itself and you were able to successfully use Remote Start on the iOS app. This tells us that it was most likely an issue with that specific authorization token set. It seems as though Tesla specifically blocked you from engaging Remote Start with that old token.

It does seem that you are still having issues on the watch app, however I suspect this is because the watch app didn't successfully receive your new authorization info from the iOS app after signing out and back in. This could be corrected by simply going to Preferences in the iOS app and tapping "Refresh watch app". This should force update the watch app to the new authorization token set. If that does not work you might have to force close & reopen the watch app and/or sign out and back in again.

Now given that your circumstance is quite rare, I'd like to extend an invite out to you to be a part of the Watchla beta, where we can learn from and better understand this unique issue and develop/test changes that help address it and ensure that it doesn't happen again to you or others. If this interests you, please send me your email to david@watchla.app or https://watchla.app/contact and I will have a beta invite sent over to you.

**Comment by Pdog135** [comment]
I followed those steps and it did not work also

**Comment by itsMeDavidV** [comment]
@Pdog135 Just a heads up, I replied to your email and also had a TestFlight invite to the beta emailed to you. Please email me or reply here if you have any questions!

**Comment by Pdog135** [comment]
It still does not work with the beta app

**Comment by itsMeDavidV** [comment]
@Pdog135 Yep as I mentioned in email, there are updates coming to beta tomorrow morning (PST) that will directly address some of the issues you face.

Thanks for your patience.

**Comment by itsMeDavidV** [comment]
@Pdog135 So after further review of the logs associated with your support code, I've identified that Tesla is explicitly requiring that you re-log in as they are responding to your Tesla API requests with the following message: `"error": "login_required"`. 

Re-logging in should immediately resolve your issues, however there are still Watchla updates rolling out to address the issue that you faced originally.

Before re-logging in, please make sure that you are fully logged out of both the iOS and Watch apps.

**Comment by Pdog135** [comment]
Thank you so much for you help. It did work correctly. I will share this
app with my Tesla community and wish nice things for you. You went above
and beyond to fix this and I appreciate i.

**Comment by itsMeDavidV** [comment]
You're very welcome! I'm glad it all worked out :)

**Comment by Pdog135** [comment]
It is in the body of the email
