### ISSUE TITLE
watchla app won't authenticate on iwatch

### ISSUE THREAD

**Issue by MarianKoleff** [itsMeDavidV/Watchla-Support#77]
For some reason the iwatch app keeps telling me to authenticate the ios app with tesla.com. I’ve signed out and logged in again and the issue persists.

My code: RARvPWBeJs

**Comment by itsMeDavidV** [comment]
Hi @MarianKoleff sorry to hear of this. Since your Apple Watch and iPhone are not communicating properly you may have different support codes for the watch and iOS apps. If they are different, can you also provide the support code listed in the watch app? You can find it right from the Sign In screen on the watch app by scrolling down, tapping "Support" and then "Support Code".

From your iOS error logs it does appear that you are having a communication disruption. These disruptions can be sometimes caused by pairing issues between your iOS device and your Apple Watch. 

Here's a helpful link on how to determine whether or not your iOS device and Apple Watch are experiencing pairing issues: https://support.apple.com/en-us/HT205025

If you are experiencing pairing issues as indicated above or if this issue persists, it might be best to re-pair your Apple Watch or at the very least restart both your Apple Watch & iOS device.

Once I hear back from you on whether or not your Apple Watch has a different support code, I should be able to understand the full scope of things and better advise.

-David

**Comment by MarianKoleff** [comment]
I've re-paired the iwatch and it works now.

**Comment by itsMeDavidV** [comment]
Awesome, I'm glad to hear that this issue was resolved. Please don't hesitate to reach out if you have any questions or feedback.
