### ISSUE TITLE
Watch icons Apple Watch Ultra

### ISSUE THREAD

**Issue by lieberfla** [itsMeDavidV/Watchla-Support#82]
The watch complication icons are not displaying on the Apple Watch Ultra. I’m guessing you know this, hoping for an update soon.

**Comment by itsMeDavidV** [comment]
Hi @lieberfla sorry to hear about this. Have you tried deleting and re-installing Watchla on both devices to rule out a bad download?

There is one other instance of this issue reported in issue #80.  

In an effort to consolidate everything I'm going to provide updates there and I encourage you to subscribe to that issue so that you can stay informed.

In the meantime, as I mentioned in the above thread, a series of Apple Watch Ultra specific fixes have been implemented in beta. If you'd like to be included in the beta to see if these change solve the complication issue you face, please feel free to email me here: david@watchla.app and I'd be happy to send you a TestFlight invite.

Sorry for this inconvenience, please bear with me as a solution is worked out.

**Comment by itsMeDavidV** [comment]
Hi @lieberfla just wanted to give you a heads up that this issue has been reproduced and fixed and the fix will be included in the next App Store update of Watchla (v2.99) in the coming days.

Sorry again for the inconvenience this has caused.

https://github.com/itsMeDavidV/Watchla-Support/issues/80#issuecomment-1327949978

**Comment by itsMeDavidV** [comment]
@lieberfla v2.99 was just released. It contains the fix for this issue. It may take 30 minutes or so from the time of this comment to be available in the App Store. Sorry again for the inconvenience this has caused.

-David

**Comment by lieberfla** [comment]
Thanks, David. Much appreciated. Sent from my iPhoneOn Dec 6, 2022, at 11:29 AM, David Villegas ***@***.***> wrote:﻿
Closed #82 as completed.

**Comment by itsMeDavidV** [comment]
You're very welcome!
