### ISSUE TITLE
#RESOLVED   __  Siri Ok shortcuts on IOS but not on Watch OS

### ISSUE THREAD

**Issue by Eldoc62** [itsMeDavidV/Watchla-Support#87]
Hello,

I added 2 shortcuts that work fine from my iPhone, I followed the FAQ to add from "details" and switch ok "Show on Apple Watch". The problem is that I restarted the Shortcuts app on both devices. I even restarted the iPhone and Apple Watch, nothing to do the shortcuts do not appear on the Apple Watch so do not work.

I'm on IOS 16.1.2 and Watch OS 9.1 and Watchla 2.99.1

**Comment by itsMeDavidV** [comment]
Hi @Eldoc62 sorry to hear that. Is this issue still occurring? 

And to clarify, are you seeing the Watchla Shortcuts in the Shortcuts app on your Apple Watch's Shortcuts app? Or are they not populating at all?

You may have to delete and re-install the Watchla watch app (& maybe even the iOS app) so that your Apple Watch can re-register those Shortcuts. 

Unfortunately this is a well-known issue with Apple's Shortcut's app where Shortcuts don't transfer successfully from the iOS device to the watchOS device. 

It also might be worth noting that it can be helpful in this situation to toggle iCloud Sync for Shortcuts off and then back on

Here's a helpful article that details how to do that (disregard non-related content): https://www.idownloadblog.com/2022/04/15/how-to-fix-shortcuts-not-working-iphone-ipad/#Disable-and-enable-Shortcuts-iCloud-Sync

Also here is an Apple Support article on how to access your iCloud sync toggle for Shortcuts: https://support.apple.com/guide/shortcuts/sync-shortcuts-apdb3a4240b0/ios

Hope this helps! Please reach out if you have any questions.

-David

**Comment by Eldoc62** [comment]
Hello and thank you for the help. 
Indeed it was a problem with iCloud and not the application, everything is back to normal, thank you

**Comment by itsMeDavidV** [comment]
Awesome, I'm very glad to hear that!

If possible, can you detail the specific steps you took to remedy this issue so that others in your position might be able to replicate those steps?

Thanks! (Closing this)

**Comment by Eldoc62** [comment]
Hi 

I do that :

https://www.idownloadblog.com/2022/04/15/how-to-fix-shortcuts-not-working-iphone-ipad/#Disable-and-enable-Shortcuts-iCloud-Sync

Disable / enable on iCloud 

Thanks
