### ISSUE TITLE
watchla.app TLS Certificate has expired and you have HSTS enabled so exceptions can't be added.

### ISSUE THREAD

**Issue by zunzster** [itsMeDavidV/Watchla-Support#91]
Cert Validity shows:
Not Before: Fri, 03 Dec 2021 20:17:21 GMT
Not After: Wed, 04 Jan 2023 20:17:21 GMT

**Comment by zunzster** [comment]
> No description provided.
Cert Validity shows:
Not Before:  Fri, 03 Dec 2021 20:17:21 GMT
Not After: Wed, 04 Jan 2023 20:17:21 GMT

**Comment by itsMeDavidV** [comment]
@zunzster Thanks for pointing this out, will address this issue.

**Comment by zunzster** [comment]
Cool. I've just bought Watchla for myself and my wife. I'm liking the app a lot overall and just waiting for v3 to see if the intermittent 408 errors go away. They mostly affect my wife with her Model Y leading her to distrust the app but I've seen them occasionally too with my Model 3. We don't have Sentry mode on at home, so it's probably the deep-sleep wakeup timeout issue.

**Comment by zunzster** [comment]
My support code is CCg6jlzzWd if you want to view the logs at your end. I can get my wife's support code too if you'd like to view it.

**Comment by zunzster** [comment]
It just took about 5-8 seconds to unlock the charge port. It's usually quicker than that. My ping to tesla.com is 348ms which is pretty bad for our fibre broadband to the US - nytimes.com is 13ms if that helps.

**Comment by itsMeDavidV** [comment]
> Cert Validity shows:
> Not Before: Fri, 03 Dec 2021 20:17:21 GMT
> Not After: Wed, 04 Jan 2023 20:17:21 GMT

This has since been fixed, thank you for reporting this!

**Comment by itsMeDavidV** [comment]
> It just took about 5-8 seconds to unlock the charge port. It's usually quicker than that. My ping to tesla.com is 348ms which is pretty bad for our fibre broadband to the US - nytimes.com is 13ms if that helps.

Wow this is an interesting contrast. Watchla doesn't track ping times in its error logs but it definitely should. As for you and your Wife's 408 issues this is most likely due to your vehicle falling into deep sleep. As you may already know, a 408 status code indicates a timed out response from your vehicle. It could also be because of your vehicles' connections to Tesla servers. I would be happy to take a look at your error logs and report back, as well as your wife's if you send over her support code. 

I am happy to report that V3 will eliminate the side effects of a 408 for most command based use cases like unlock charge port and you are welcome to join the V3 beta as it is currently temporarily open, just let me know and I will send over an invite. For more info on that, see here: https://twitter.com/WatchlaApp/status/1608964323686387713?s=20&t=JE-n07fwn4uTOyiDDNUesA
