### ISSUE TITLE
Bluetooth setup not working

### ISSUE THREAD

**Issue by SMTeslaMY** [itsMeDavidV/Watchla-Support#96]
I keep getting Bluetooth not enabled error when trying to set up the app. 
Bluetooth is enabled on the watch. I have already deleted the app from watch and reinstalled it. Toggled Bluetooth on and off. The error doest go away and I can't complete the Bluetooth configuration. 
Apart from this app works great.. I am able to submit all commands and use it the app fine. Any suggestions, how to fix this? 
![08BC2F7B-10FF-4A65-B3F4-902E64E0B9D2](https://user-images.githubusercontent.com/123209549/213805064-197fc9ef-f5bc-4654-9baa-a52efeeee408.jpeg)

**Comment by anniej42** [comment]
also unable to connect via bluetooth on my 2020 MY. After `initializing...`, the watch app gets stuck on the `waiting` page and then fails with a timeout.

**Comment by itsMeDavidV** [comment]
Hi @SMTeslaMY the screenshot you included indicates that you did not enable Bluetooth permission for Watchla.

To fix this all you have to do is on your paired iOS device, open the Settings app and then scroll down and tap Watchla and then enable Bluetooth.

Here's a screenshot for reference:

![image](https://user-images.githubusercontent.com/12491192/213808534-3292680b-b6ee-4032-9b9a-08b305ff083c.png)

**Comment by itsMeDavidV** [comment]
> also unable to connect via bluetooth on my 2020 MY. After `initializing...`, the watch app gets stuck on the `waiting` page and then fails with a timeout.

Hi @anniej42 if you don't see a screen like the one included below, you might be experiencing a UI bug. In which case when you try to set up Bluetooth, be sure to place your Key Card below the center console (like in the screenshot below).

If that doesn't work, it might be because of an issue with Watchla failing to match your Selected Vehicle to the vehicle you are trying to connect to over Bluetooth. If this seems to be the case, please let me know and this will be investigated promptly.

Screenshot:

<img width="419" alt="Screenshot 2023-01-20 at 2 30 44 PM" src="https://user-images.githubusercontent.com/12491192/213809351-e907c508-04ab-4145-9f75-3d17b87e7cfa.png">

**Comment by SMTeslaMY** [comment]
> Hi @SMTeslaMY the screenshot you included indicates that you did not enable Bluetooth permission for Watchla.
> 
> To fix this all you have to do is on your paired iOS device, open the Settings app and then scroll down and tap Watchla and then enable Bluetooth.
> 
> Here's a screenshot for reference:
> 
> ![image](https://user-images.githubusercontent.com/12491192/213808534-3292680b-b6ee-4032-9b9a-08b305ff083c.png)

Thanks. That fixed it

**Comment by itsMeDavidV** [comment]
> Thanks. That fixed it

That's good to hear! Please reach out if there are any other issues or you have any questions. I'll keep this open incase @anniej42 's issue is till not solved.

**Comment by anniej42** [comment]
unfortunately still the same issue

**Comment by anniej42** [comment]
![F2E9F6BE-315D-4027-9B23-5A47479217ED](https://user-images.githubusercontent.com/3856345/213889906-d6677c63-4d80-4474-a12a-37bfbb4d3a98.jpeg)

**Comment by itsMeDavidV** [comment]
Hi @anniej42 you might need to sign out and sign back in. This will delete and reset your Bluetooth data.

Also ensure that Allow Mobile Access is enabled on the vehicle touchscreen (Controls > Safety > Allow Mobile Access).

Sorry for the inconvenience, please let me know how this goes.

**Comment by anniej42** [comment]
unfortunately I still have the same issue. Once it went from `Waiting..` to `Connecting..`, but then went back to waiting.
Mobile access is enabled.

**Comment by itsMeDavidV** [comment]
Ok, just to confirm you signed out and signed back in and the issue persisited, correct?

I suspect there is an issue that occurred when Watchla attempted to whitelist its key with your Tesla. It should have corrected itself, but it seems it failed to. Unfortunately, since this feature is so new there is no specific error logging for this specific event. However this is being added as well as an audit as there are now 2 reported cases of this issue occurring (you and another person). 

Would you like to switch over to Watchla's beta app so that we can test changes to the Whitelist process that might remedy this issue for you? If so, please send over your Watchla support code to my email here: david@watchla.app and I'll get you added in asap.

Sorry again for the inconvenience this causes, I know this must be frustrating. If you would like to stay on the production app, an alternative workaround I'd recommend would be to sign out + delete/re-install Watchla, but again there is an issue to be corrected here and others in the future could greatly benefit by Watchla better understanding and correcting this issue.

**Comment by anniej42** [comment]
will send you an email, thanks!

**Comment by bvstoronto** [comment]
I also Janet he same issue. Tried all u have mentioned here many times. I have sent u an email as well

**Comment by itsMeDavidV** [comment]
Hi @bvstoronto sorry to hear that. We are currently in the process of fixing this issue. Would you be open to joining Watchla's beta group to test changes that address this issue? If so, I will have a TestFlight invite to the beta app emailed over to you.

**Comment by bvstoronto** [comment]
Hi David 
Thank u so much for the immediate response!!!!

Sure I can join the beta group and test it out
I just purchased it yesterday and So far I love this app :)

**Comment by itsMeDavidV** [comment]
@bvstoronto awesome I'm very glad to hear that you like Watchla!

I've sent you an email as well as had a TestFlight invite to the beta app emailed over to you.

**Comment by bvstoronto** [comment]
> 
@anniej42  Could you please let me know if Bluetooth setup  is working for you now? if so please let me know how did u resolve it?

**Comment by bvstoronto** [comment]
> @bvstoronto awesome I'm very glad to hear that you like Watchla!
> 
> I've sent you an email as well as had a TestFlight invite to the beta app emailed over to you.

@itsMeDavidV  I tried the beta version. unfortunately still the same issue. it is stuck with  Initialising and Waiting... message

**Comment by itsMeDavidV** [comment]
Hi @anniej42 I just wanted to update you to let you know that a new Watchla update (v3.02) has been released that fixes an issue similar to what you have described here. 

You can update here: https://apps.apple.com/us/app/watchla/id1546599747 as well as in beta.

Please do let me know if this new update resolves this issue for you!
