### ISSUE TITLE
Unable to pair Apple Watch ultra

### ISSUE THREAD

**Issue by Pchornung** [itsMeDavidV/Watchla-Support#99]
It keeps saying waiting when trying to pair

**Comment by itsMeDavidV** [comment]
This might be because of a UI bug that fails to to show the following screen (see below) in very infrequent cases.

If this is the case, all you need to do is tap your keycard under your center console, like in the screenshot below.

Also make sure that: 
- your Selected Vehicle is the vehicle your trying to connect to 
- that your vehicle supports Phone Key [(see tweet about this)](https://twitter.com/WatchlaApp/status/1616535957666410496?s=20&t=6MIYm2R1Y7DhO2YgcXR8Kw)
- And that you are inside your vehicle when trying to set up Bluetooth

<img width="419" alt="Screenshot 2023-01-20 at 2 30 44 PM" src="https://user-images.githubusercontent.com/12491192/213880866-da87f223-b986-42b2-8b96-6b021f14f4a9.png">

**Comment by Pchornung** [comment]
I’m inside the vehicle and it does not ever pass that waiting on the phone app.

My car is a 2021 model 3

I put my Tesla car key behind the cup holder and nothing still

**Comment by itsMeDavidV** [comment]
@Pchornung can you post a video of this issue occurring here in the comments so that I can better understand any errors that might be taking place? 

Thanks,
-David

**Comment by Pchornung** [comment]
Pretty simple, when in the car, I go to preferences then select manage Bluetooth, click start, click I’m ready, says initializing, then waiting, then I go to out the card near my cup holder.   Nothing happens.

**Comment by itsMeDavidV** [comment]
@Pchornung you might ultimately have to sign out and sign back in and to refresh Watchla's Bluetooth comm settings.

Also ensure that:
• Allow Mobile Access is enabled on the vehicle touchscreen (Controls > Safety > Allow Mobile Access).
• The Watchla watch app stays open and on during the entire Bluetooth setup process
• And The Selected Vehicle on Watchla is the vehicle you're trying to connect to (if you have multiple Teslas)

What seems to be happening here is that Watchla is not able to do a proper hand shake with your vehicle. This entails connecting to your vehicle, exchanging key info and sending a confirmation message.

You'll also need to make sure that you haven't reached the maximum number of keys for you vehicle (unlikely). You can check keys in the "Locks" screen.

Also if you'd like to send over your Watchla support code, I'd be happy to see if there are any associated error logs that point to an underlying issue.

**Comment by itsMeDavidV** [comment]
Hi @Pchornung I just wanted to update you to let you know that a new Watchla update (v3.02) has been released that addresses an issue similar to what you have described here. You can update here: https://apps.apple.com/us/app/watchla/id1546599747

Please do let me know if this new update resolves this issue for you!

**Comment by CassandraMarie** [comment]
Since there hasn't been a response from the original poster for a while, I'm going to close this matter. Should the issue persist or reoccur, please don't hesitate to reopen it.
